### ISSUE TITLE
Small about us in home

### ISSUE THREAD

**Issue by Darkspac3** [HDInnovations/UNIT3D#104]
Before or after "News" text html/css/php or link or anything

**Comment by HDVinnie** [comment]
Whats the point besides more clutter? The About Us page is already linked in the footer.

**Comment by Darkspac3** [comment]
but no one thinks of going away

**Comment by HDVinnie** [comment]
Closing this as there is already a dedicated About Us page......if you want to add something to home page you can do so yourself very easily. If need help just PM me.
