### ISSUE TITLE
TSSE Upgrade Script

### ISSUE THREAD

**Issue by NANO-Chile** [HDInnovations/UNIT3D#106]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

Please can someone create an script to upgrade from TSSE to UNIT3D

Thanks!

**Comment by HDVinnie** [comment]
@pxgamer might  be able to help out with this. He was nice enough to make some beautiful artisan packages to port over users and torrents from xbtit, u232 and gazelle to UNIT3D. I am sure you will have to provide him with the Depaul database schema so he can properly map it out.

**Comment by pxgamer** [comment]
I'd be happy to. Not heard of TSSE so a Schema would be useful. At least for users/torrents. 👍

**Comment by HDVinnie** [comment]
@NANO-Chile are you able to provide @pxgamer with a TSSE database dump so he can map out the schema and do testing?

**Comment by HDVinnie** [comment]
Seeing as a dump was never provided by OP I am closing this.

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/templateshares-to-unit3d
