### ISSUE TITLE
Movies&TV Subtitles and Audio Scrapper From Mediainfo Log

### ISSUE THREAD

**Issue by CoFix** [HDInnovations/UNIT3D#192]
- UNIT3D Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Please watch this video. 
https://mega.nz/#!PUh11CaY!vUqGUZg-iVprqsTRG9-x5m0Wlxaka1fw3EBsUcKEZ4c

**Comment by HDVinnie** [comment]
This is already done. Please thoroughly check demo before opening issue.
https://github.com/HDInnovations/UNIT3D/blob/master/app/Helpers/MediaInfo.php
https://github.com/HDVinnie/MediaInfo-Helper
