### ISSUE TITLE
IRC Torrent Announce System

### ISSUE THREAD

**Issue by CoFix** [HDInnovations/UNIT3D#193]
- UNIT3D Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
IRC Torrent Announce System (New torrent will announce tracker irc channel)
https://malzo.com/i/2017/06/16/bnDMgDme7e9b1.png

**Comment by HDVinnie** [comment]
Should be easy enough.....ill look into this after finishing up some other open branches I have.

**Comment by HDVinnie** [comment]
So I have mocked up some code but don't have a IRC server. Anyone have one I can use to test on?

**Comment by HDVinnie** [comment]
07abf8c0b19745fe5cc2f4f8e8e022297eb6e066

**Comment by gjm1976** [comment]
i have if you need one to test on
