### ISSUE TITLE
Make Torrent Freelech with karma points in details page

### ISSUE THREAD

**Issue by CoFix** [HDInnovations/UNIT3D#194]
- UNIT3D Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
https://malzo.com/i/2017/06/16/AZqqxlnpec686.png

Watch This -> https://mega.nz/#!uMgXkRbL!G04HWVTQVMTURU0eM6_sFqLLmCQxiedEEJ8qWrDIpdM

**Comment by HDVinnie** [comment]
There are already way to many ways to get free leech. Nor is there a karma point system. Nor do I see a good point to add one. Your simply taking images / video from xbtit and u-232 powered sites. Be creative my friend.
