### ISSUE TITLE
A way to predifine some things the bot says in the shoutbox

### ISSUE THREAD

**Issue by gjm1976** [HDInnovations/UNIT3D#208]
The random stats on the bot in the chatbox are cool, I was wondering if there was a way we could put some lines in a file that it would randomly pick as well, like some site notices that need repeating randomly...

**Comment by HDVinnie** [comment]
Your free to add more. The shouts by bot are randomly picked from the /commands/autoNerdStat.php

However I will try to add more defaults.

**Comment by HDVinnie** [comment]
More defaults have been added over time. Guys can add more on your own in `commands/autoNerdStat.php`.
