### ISSUE TITLE
Improve "Similar Torrents" list

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#213]
The similar torrents list seem to always show the same torrents for every torrent.

It probably should list files with similar names or from the same category.

**Comment by Hyleus** [comment]
No. It should only shows torrents for the same movie or TV show, so you can compare the differences between them easier. It's not for finding torrents that are similar in title, more so for finding torrents that are equivalent in IMDB or TMDB ID.

**Comment by HDVinnie** [comment]
similar torrent are torrents that have the same IMDB number. So if your not enforcing your members to use a proper IMDB number besides zero then thats your issue.....
