### ISSUE TITLE
Reannounce button on torrent info screen

### ISSUE THREAD

**Issue by gjm1976** [HDInnovations/UNIT3D#216]
On each torrent info screen, near where grantfl, feature torrent buttons are, have a reannounce button which just shouts the torrent in chatbox and irc again (this is espiecially user for irc, as lots of users have auto-dl bots that scan announce channels and download anythings that announced....,, so if something needs more seeders... re-announce ;) )

it also would add fresh interest in the torrent.

**Comment by gjm1976** [comment]
could say something like : torrent title , torrent link is currently being reintroduced to you all

**Comment by gjm1976** [comment]
also handy if when a upload happens the shoutbox and irc don't work (has happened to me lately) and it would make them shout about the torrent

**Comment by HDVinnie** [comment]
hmm ill have to think of a better way to word it and go from there.

**Comment by gjm1976** [comment]
or click reannounce and then it asks for a reason and could have as new upload, as refresh upload etc.

new upload could be normal announce , refresh could be : title , link needs more seeders so were reannouncing

**Comment by gjm1976** [comment]
maybe it could also work as a incentive to seed as well, so if reannounce , refresh torrenet, it announces it needs more seeder and also offers bonus point for people who reseed it
