### ISSUE TITLE
Sort torrent categories alphapetically and not by ID

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#219]
it seems like the categories are sorted by ID, which makes it very difficult to add new categories and sort them alphapetically by hand when there are already torrents in a category that needs to be edited, in order to move the new cat to the new place.

**Comment by HDVinnie** [comment]
I can make it like types where it goes by a custom set position number. That way it's not locked to id or alphabetically and is more flexible for all

**Comment by xR4E** [comment]
That would also be great. 👍
