### ISSUE TITLE
Apply for membership system

### ISSUE THREAD

**Issue by gjm1976** [HDInnovations/UNIT3D#220]
When site is closed, and users aren't sending invites... a apply for membership option on the login screen would be handy, where people get asked questions like, are you on any other trackers, please provide links and screenshots to your member profile showing ratio etc....

And in the staff dashboard as section where staff can approve or deny these applications.

If they get approved the system send them a email with a invite code generated by the tracker.

Also a way for people to track to see if their application has been seen or processed yet.

**Comment by HDVinnie** [comment]
This was added and closed in https://github.com/HDInnovations/UNIT3D/pull/531
