### ISSUE TITLE
Configure the scrapers per category

### ISSUE THREAD

**Issue by ghost** [HDInnovations/UNIT3D#222]
It would be nice if that could be configured, so for example for videos IMDB and TMDB and then maybe fall back to a manual mode if there's not scraper that fits for that category, like for games.

**Comment by HDVinnie** [comment]
UNIT3D is aimed for Movies and TV. One can add other categories like Apps, Games, Music and make sure `Has Meta Data? (Movie/TV)` Yes `No`when creating the categories. Then no meta views will display.
