### ISSUE TITLE
Add an option to restrict invites

### ISSUE THREAD

**Issue by Hyleus** [HDInnovations/UNIT3D#226]
Some sites might want to restrict it to a certain user class while others might even make it staff only. Adding two new options: restrict_invites stores a bool and invite_groups which stores an array of userclass names would solve that. So, if restrict_invites is set to true then only the userclasses mentioned in invite_groups can invite.

**Comment by HDVinnie** [comment]
Sounds good to me. You thinking of doing it via config or in DB with a whole new view in staff dashboard to adjust invite settings? Feel free to make a PR.
