### ISSUE TITLE
Redirect loop on unlocking account

### ISSUE THREAD

**Issue by VerioPL** [HDInnovations/UNIT3D#233]
- UNIT3D Version: latest
- Laravel Version: 5.6.3
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:
Trying to unlock account makes redirect loop

### Steps To Reproduce:
Lock account -> ./unlock -> Typing password -> Redirect loop

Unlock form sent POST to ./lockscreen/unlock, then redirect loop is 302 to ./lockscreen

### Possible Fix:
?

**Comment by HDVinnie** [comment]
Please check existing open and closed issues before creating a new one. This is a duplicate. Please see #2
