### ISSUE TITLE
Error when signup

### ISSUE THREAD

**Issue by esteban63** [HDInnovations/UNIT3D#235]
Hi,

I have an error when someone is trying to signup to my website.

I obtain this error code : Address in mailbox given [Example] does not comply with RFC 2822, 3.6.2.

Glad you can help me

**Comment by HDVinnie** [comment]
Step Six in the README install instructions:

`Edit .env.example to .env and fill it with your APP, DB, REDIS and MAIL info.`


Example for mail section:

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.stealth.tg
MAIL_PORT=587
MAIL_USERNAME=blah@stealth.tg
MAIL_PASSWORD=paswordhere
MAIL_ENCRYPTION=tls
MAIL_FROM_NAME=blah@stealth.tg
MAIL_FROM_ADDRESS=blah@stealth.tg
```

In your case `MAIL_FROM_ADDRESS=` needs to be a actual mail address and not just example.

**Comment by esteban63** [comment]
Thanks a lot
