### ISSUE TITLE
Gazelle Upgrade Script

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D#24]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Looking for someone that can make a script to port over a gazelle database dump into UNIT3D. Im thinking mainly torrents and users are most important and probably only ones worth it? Thoughts?

### Steps To Reproduce:
N/A

### Possible Fix:
N/A

**Comment by pxgamer** [comment]
I may have a look at this.

By the way, this project is pretty cool. It has a similar look to PrivateHD which is nice. :+1:

**Comment by Hyleus** [comment]
@pxgamer Could you write it in a scripting language (ie in Python or Ruby) so that it can be used cross-platform?

**Comment by pxgamer** [comment]
Any reason to not have it in PHP which is cross-platform?

**Comment by Hyleus** [comment]
That would be even better, I just wasn't sure in what language you want to write it.

**Comment by pxgamer** [comment]
Oh cool. That's good. :smile: I'll have a look later today.

**Comment by pxgamer** [comment]
Had a look and started working on a repo (I was going to have it as a dev dependency package).
https://github.com/pxgamer/gazelle-to-unit3d/tree/develop

I've hit a wall though as for some reason, Gazelle isn't correctly getting the info hash of uploaded files.

Do any of you have an example DB for Gazelle?

In the mean time, I may look into #19 and #23.

**Comment by Hyleus** [comment]
@pxgamer I'll try to generate a DB dump after I've looked at it myself. Maybe we can autofill it with randomly generated data so that it matches realistic conditions. After I've made I'll publish it on a separate repo so it can be used by everyone.

**Comment by HDVinnie** [comment]
this is exciting....thanks @pxgamer

**Comment by pxgamer** [comment]
Well, it seems to be working.

I'll test it again when the database dump is done. :+1:

**Comment by HDVinnie** [comment]
Done. Further support should be carried out here. https://github.com/pxgamer/gazelle-to-unit3d
