### ISSUE TITLE
Ability to reupload a .torrent file

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#240]
Hi,

when I moved my server there were a few torrents which were missing in the "files" system.
So I had to upload them via FTP and rename them like they are named in the DB.

Maybe it can be implemented to the edit blades, so (or others) can replace the .torrent file without needing to delete and then repost it. May be helpful when the .torrent is broken or something.

**Comment by HDVinnie** [comment]
Im not sure this is possible. Do you know of other sites that have this ability and if so what codebase?
