### ISSUE TITLE
Display tracker url in place of ip address in torrent announce

### ISSUE THREAD

**Issue by esteban63** [HDInnovations/UNIT3D#241]
Hi,

All is in the title.
When someone downloads a .torrent file, in his torrent client, it appears the ip of my server and I want it to be the url of my site.

Thank's

**Comment by HDVinnie** [comment]
Sounds like a issue your end. 

The announce displays as https://yourdomian.com/userpidhere

Are you sure you have your APP_URL= Set properly in your env?

**Comment by HDVinnie** [comment]
How about in your NGINX config? For server_name? Using IP or domain?

I'm not able to replicate this on demo, local or production.

**Comment by HDVinnie** [comment]
Also try running php artisan config:clear

**Comment by pxgamer** [comment]
As far as I know, `APP_URL` is only used in CLI. (I may be wrong about that)

I think that as mentioned this is probably an issue with nginx or whatever web server is being used. 👍

**Comment by esteban63** [comment]
It's not my nginx config, I use the recommanded config with server_name blablabla.com

**Comment by pxgamer** [comment]
Never mind, I just re-read your initial message body. 👍

**Comment by esteban63** [comment]
Nope on the website every links uses the URL, it's only the announce

**Comment by HDVinnie** [comment]
Be honest I'm stumped on this one. As @pxgamer pointed out there all route based. I have tried replicating this on demo, production and local with no joy. Also went on a few other people's production sites using UNIT3D and there announce also shows domain. 

Anyone else facing this issue?

**Comment by pxgamer** [comment]
Interesting. :thinking: I can't work this out, but I'll look into it a bit later. :+1:

**Comment by HDVinnie** [comment]
That's the comment. Different from this topic. You can change the comment and source flag in the config/torrent.php

**Comment by HDVinnie** [comment]
Under trackers in your screenshot. This part you have cut out shows your domain name right? That's what this issue is about. OP states it shows his IP like https://1.2.3.4/announce/pid instead of https://mydomainhere.com/announce/pid

**Comment by Alastor-NBL** [comment]
HDVinne yes, that is correct it shows my domain name and **NOT** the IP address.

**Comment by HDVinnie** [comment]
@esteban63 any luck? After hours of testing I CANNOT replicate this using latest code from master. Seeing no one else is facing this issue either, it leads me to have no choice but to mark this invalid and close the issue. Unless you can prove otherwise?

**Comment by esteban63** [comment]
I finally give up and re-install the tracker and with the same config, it's finally work. Thank's for trying :)
