### ISSUE TITLE
Footer Image is not rendering correctly

### ISSUE THREAD

**Issue by Alastor-NBL** [HDInnovations/UNIT3D#243]
- UNIT3D Version: "UNIT3D" Nex-Gen Torrent Tracker v1.6.1
- Laravel Version: Laravel Framework 5.6.12
- PHP Version: PHP 7.2.3-1+ubuntu16.04
- Database Driver & Version: 5.7.21-0ubuntu0.16.04.1

### Description:
It appears that the footer image is not rendering correctly on the home page.
![untitled-2](https://user-images.githubusercontent.com/37871080/38136331-f5399848-341d-11e8-889f-ea0e4593a112.png)

### Steps To Reproduce:
As you can see the image has gone behine the Navigation menu on Home page.
However, checking other pages the image seems to render and fit perfectly.

### Possible Fix:
Dunno

**Comment by pxgamer** [comment]
On the index, the `#l-footer` element is outside the `#hoeapp-container` div.

It looks like on the other pages `#l-footer` is inside the `#main-content .inner-content` div. When `#l-footer` is moved inside the `.inner-content`, it seems to render the same as the other pages.
