### ISSUE TITLE
Text Box is collpased and not open

### ISSUE THREAD

**Issue by Alastor-NBL** [HDInnovations/UNIT3D#246]
- UNIT3D Version: "UNIT3D" Nex-Gen Torrent Tracker v1.6.1
- Laravel Version: Laravel Framework 5.6.12
- PHP Version: PHP 7.2.3-1+ubuntu16.04
- Database Driver & Version: 5.7.21-0ubuntu0.16.04.1

### Description:
![untitled-2](https://user-images.githubusercontent.com/37871080/38138778-d8bde1e2-342c-11e8-9c65-8bea08506321.png)

### Steps To Reproduce:
I noticed this whilst editing the Upload Rules page when I needed to insert a link and am required to first type in the title. It's a bit icky and once you have managed to type the first letter he text box then opens up as normal.

### Possible Fix:
Beats me I am leaving it to you guys.

**Comment by HDVinnie** [comment]
Im not seeing this......not able to replicate it on demo site.

Can you try again? Maybe was a glitch? Clear your browser cache and also try running `php artisan view:clear` and `php artisan cache:clear` for the hell of it.

**Comment by pxgamer** [comment]
Interesting :thinking: I'm unable to replicate this issue.

**Comment by Alastor-NBL** [comment]
Okay so I checked it in Google Chrome no issues.
I checked it in Microsoft Edge no issues
It is only happening with Firefox Quantum 59.0.2 (64-bit) on Windows 10
