### ISSUE TITLE
Unable to quote a post in forums

### ISSUE THREAD

**Issue by ghost** [HDInnovations/UNIT3D#247]
- UNIT3D Version: "UNIT3D" Nex-Gen Torrent Tracker v1.6.1
- Laravel Version: Laravel Framework 5.6.12
- PHP Version: PHP 7.2.3-1+ubuntu16.04
- Database Driver & Version: 5.7.21-0ubuntu0.16.04.1

### Description:
Unable to quote any users post in the forum

### Steps To Reproduce:
Please visit the forum and click on the quote button. Nothing happens.

**Comment by HDVinnie** [comment]
Im going to mark this as a feature request as it was never implemented. It simply a button with no logic.

**Comment by poppabear8883** [comment]
Just took a look at this and this would be quite difficult with the current implementation. This is where VueJS could shine!

**Comment by HDVinnie** [comment]
I think there is a not to hard way using the wysibb editior we use.

http://wysibb.com/docs/p6.html
http://wysibb.com/docs/p2.html

I just haven't had time to look fully into it.
