### ISSUE TITLE
Pending torrents inconvenience, disable invite codes perhaps not quite bugs though.

### ISSUE THREAD

**Issue by Zorkel** [HDInnovations/UNIT3D#248]
- UNIT3D Version: #.#.# 1.6.1
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Might not be issues/bugs per say possibly more lacking features or perhaps internal link oversights?
Would like the ability to disable invite-codes that has been generated, currently not aware of how that can be done. :)

As administrator I also get messages at the top of dashboard I have xxx torrent pending. But clicking on the torrent does nothing, so I have to go to staffdashboard to find the torrent. Would be really nice if the icon/link would take me to the torrent dashboard is pestering me with.

### Steps To Reproduce:

x
### Possible Fix:
x

**Comment by HDVinnie** [comment]
1) When you have a pending torrent via moderation simple click the icon and then view all which will redirect you to the moderation page. The torrent name is not linked to anything in the dropdown. Just simply there to show you the name of the torrent and or torrents pending moderation.
[img]https://i.imgur.com/D9VQil5.png[/img]

2) There is not reason to really delete a invite code. They by default expire after 14 days and are recycled. However I will push a commit in a few so one can configure the expire/recycle time.
