### ISSUE TITLE
Unable to view NFO

### ISSUE THREAD

**Issue by Alastor-NBL** [HDInnovations/UNIT3D#250]
- UNIT3D Version: "UNIT3D" Nex-Gen Torrent Tracker v1.6.1
- Laravel Version: Laravel Framework 5.6.12
- PHP Version: PHP 7.2.3-1+ubuntu16.04
- Database Driver & Version: 5.7.21-0ubuntu0.16.04.1

### Description:
Unable to view NFO file

### Steps To Reproduce:
Clicking on the NFO button in details doesn't do anything.
Am I missing something?

### Possible Fix:
Dunno

**Comment by HDVinnie** [comment]
The code for being allowed to upload a NFO file is disabled until further notice. Why the button does nothing for you.

**Comment by Alastor-NBL** [comment]
Okay that explains it thanks!
