### ISSUE TITLE
Installation Debian ?

### ISSUE THREAD

**Issue by Titeuf49** [HDInnovations/UNIT3D#252]
Hello,
Can this version be installed under debien 8?
if yes what is the installation procedure please.
In advance, thank you for your answers

**Comment by HDVinnie** [comment]
I haven't tested it under Debien 8 but it should work just fine. As for install procedure it should be same. 

This has only been tested by me with Ubuntu/CentOS and MySQL/MariaDB

**Comment by Titeuf49** [comment]
Hello,
thank you for your answer, if it works with debian I will test the installation and I give you a message here!

**Comment by HDVinnie** [comment]
Sounds good.
