### ISSUE TITLE
Invite token+ config/mail.php

### ISSUE THREAD

**Issue by xxx31fr** [HDInnovations/UNIT3D#253]
- UNIT3D Version: the lastest
- Laravel Version: 5.6.15
- PHP Version:7.2.4
- Database Driver & Version: Ver 14.14 Distrib 5.7.21-20

### Description:
1.I can connect with the user setup in .env file.
in config/other.php I setup registration: "invite only"
But, on the front end, I cannot invite someone, it says that I have not invite token.
How can I add invite token?

2. Must I modifiy the settings in mail.php with my own settings, because all is "by default"?

Thanks

**Comment by HDVinnie** [comment]
1) As in the instructions of README.md you MUST fill in your MAIL info in the .env file. You do not need to mess with the mail.php config.

2) In order for many functions to work like invites (invite and activation email must send), open reg (activation email must send), and others you need a valid SMTP for step one above.

3) Once you have done that you can either set `config/other.php` 'invite-only' => false, for open registration or leave it at true and send invites by going to your Profile->Invites Button(mid way down page)

**Comment by HDVinnie** [comment]
If you need to add invites to your main account then goto `Staff Dashboard->User Gifting` and gift yourself invites.....

**Comment by xxx31fr** [comment]
I will try that
i'll reply with the result

**Comment by xxx31fr** [comment]
Is it possible to disable "can invite" for some users?
when a user is created, in which group is he, group "user"?
If I want to move user from a group to another group, how can i do?

Many Thanks

**Comment by HDVinnie** [comment]
1) goto the users profile->click edit user->click permissions tab

2) when a user is created they are out in validating group which is restricted until they activate there account at which time they are transferred into the Member group.

3)  go to the users profile. Click edit user. Select their new group and save This is all very simple stuff. I highly suggest you bring up the codeBase for yourself and spend a few days going through it . any other questions just let me know.
