### ISSUE TITLE
Wishlist/Watchlist System

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D#255]
A page where a user can add a wishlist item which will require a IMDB + TMDB number. This wished item must not be present on site. Meaning not torrents can exist with said IMDB + TMDB number. Once a torrent is uploaded with wished IMDB + TMDB number then said user will be notified of said upload that matches there wish listed IMDB + TMDB number.

Make sense? This was requested by a user on a site running UNIT3D.

**Comment by poppabear8883** [comment]
v1.0 Beta daaa673c45bf699668113cbe9527939155620e2e

Sorry, forgot to reference this in the commit message.

Notifications for granted wishes are coming up next.
