### ISSUE TITLE
Remove Certain Fields

### ISSUE THREAD

**Issue by DuR4c3ll** [HDInnovations/UNIT3D#258]
- UNIT3D Version: "UNIT3D" Nex-Gen Torrent Tracker v1.6.1
- Laravel Version: Laravel Framework 5.6.12
- PHP Version: PHP 7.2.3-1+ubuntu16.04
- Database Driver & Version: 5.7.21-0ubuntu0.16.04.1

### Description:
Remove certain fields and not exactly an issue with code but would appreciate some help, please.

### Steps To Reproduce:
On the upload page and details page etc I am looking to hide the TVDB and MAL totally I do not need those. I tried commenting that out in `resources/views/torrent/upload.blade.php` it breaks the upload page as torrent will not upload. I did use correct comment tags 

### Possible Fix:
You tell me lol

**Comment by HDVinnie** [comment]
`
            <div class="form-group">
                <label for="name">TVDB ID <b>(Optional)</b></label>
                <input type="number" name="tvdb" value="0" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="name">MAL ID <b>(Optional)</b></label>
                <input type="number" name="mal" value="0" class="form-control" required>
            </div>
`

To

`
            <div class="form-group">
                <label for="name">TVDB ID <b>(Optional)</b></label>
                <input type="hidden" name="tvdb" value="0" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="name">MAL ID <b>(Optional)</b></label>
                <input type="hidden" name="mal" value="0" class="form-control" required>
            </div>
`

**Comment by HDVinnie** [comment]
Um seems you did not do in full what I said above.

**Comment by DuR4c3ll** [comment]
Oh shyte sorry will get on it now

**Comment by DuR4c3ll** [comment]
HDVinnie I would also like to hide them on the browse page too under Current Filters along with Category. Category is moot as we only have one category.

Thanks

**Comment by HDVinnie** [comment]
Bud this is not issue/bug/feature related to UNIT3D. This is custom work you want to suit your needs. Please keep stuff like this to discord channels.
