### ISSUE TITLE
Remove unwanted sections

### ISSUE THREAD

**Issue by DuR4c3ll** [HDInnovations/UNIT3D#261]
This is more like a question and I need to be able to remove the parts in red boxes.
Those parts for me are moot and not needed as I only have movies.
Thanks
![untitled-1](https://user-images.githubusercontent.com/17498255/39073686-e717f8ae-44ee-11e8-9e6f-794c24893d68.png)

**Comment by HDVinnie** [comment]
As stated in your previous issue you opened:

"Bud this is not issue/bug/feature related to UNIT3D. This is custom work you want to suit your needs. Please keep stuff like this to discord channels." #general

**Comment by DuR4c3ll** [comment]
Sorry man

**Comment by HDVinnie** [comment]
Not saying I won't help you. Because I will. Just try to keep custom stuff like this to the Discord channel is all I'm asking.

**Comment by DuR4c3ll** [comment]
Oh I know and you are right. Don't worry about it at all. Thanks
