### ISSUE TITLE
Limit visibility of exception messages that appear in the custom error pages.

### ISSUE THREAD

**Issue by poppabear8883** [HDInnovations/UNIT3D#262]
### Description:
![image](https://user-images.githubusercontent.com/7263458/39085095-14aa98c8-454c-11e8-9fdb-6720be9eea85.png)

Should limit the visibility of the exception message that appears in the top left corner of the custom error pages.

### Possible Fix(s):

1. We could do something as simple as to display these messages to users with `is_modo`.

2. We could setup a debug settings section in the staff dashboard to choose to turn it on or off for `is_modo`.

3. We could setup a debug settings section in the staff dashboard to choose what role level will see it. 

Example: 3 Levels

- All
- Moderators and Owner
- Owner only

**Comment by HDVinnie** [comment]
@poppabear8883 for now I have closed this meeting option one:

"We could do something as simple as to display these messages to users with is_modo."

**Comment by poppabear8883** [comment]
Maybe we could create a new issue for Option 3 to be implemented in the 2.0 project ?

**Comment by HDVinnie** [comment]
yes that would be best.
