### ISSUE TITLE
Ability to give out warnings manually

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#268]
Some of the BLU rules state that you may get a warning for certain things.

Turns out there is no ACTUAL function to give out warnings, but only staff notes at best.

I think it may be nice to have the ability to give out warnings manually (+ reasoning) and decide for how long it should be active.

**Comment by HDVinnie** [comment]
Its verbal warnings.....the warning system is only built for the hit and run system and is all automated.

**Comment by HDVinnie** [comment]
Closing this since warning system is only built for the hit and run system and is all automated. Maybe down road can look into doing a "Strikes System" or something with manual use.
