### ISSUE TITLE
Torrent Grouping

### ISSUE THREAD

**Issue by xdamanx** [HDInnovations/UNIT3D#27]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

Feature request for torrent grouping. https://imgur.com/QJM1O7E

### Possible Fix: 
Add torrent grouping.

**Comment by Hyleus** [comment]
I've updated the Imgur URL it was pointing to https://github.com/UNIT3D/UNIT3D/issues/url so I've fixed it.

**Comment by Darkspace10** [comment]
new ? I want this feature
