### ISSUE TITLE
Process install on debian 8

### ISSUE THREAD

**Issue by Titeuf49** [HDInnovations/UNIT3D#274]
hello, 
is it possible to have the installation procedure step by step for debian 8 please?
Thank you

**Comment by poppabear8883** [comment]
@HDVinnie actually has this on his mind, we was just talking about a Wiki for UNIT3D ... This will likely be available soon enough.

@Titeuf49 you should be fine following the readme as its all Linux anyways `Ubuntu is Debian based`

**Comment by pxgamer** [comment]
Also, regarding this, I don't think it's really necessary to include most of these as separate steps.

Could just either:
- Provide a wiki page with the install instructions (perhaps a command that installs all the dependencies)
- Provide detailed install instructions, but remove them from the README to make it a bit cleaner

For example:

```bash
sudo add-apt-repository -y ppa:nginx/development ppa:ondrej/php
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get update
sudo apt-get install -y \
 git tmux vim curl wget zip unzip \
 htop nano build-essential nodejs \
 supervisor redis-server nginx mariadb-server \
 php-pear php7.2-curl php7.2-dev php7.2-gd \
 php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml php7.2-fpm
```

Or just mention which modules are required, e.g:

- nginx
- redis-server
- mariadb-server
- php 7.2 (with curl, pear, gd, mbstring, zip, mysql, xml and fpm)
- supervisor
- nodejs (8.x or above)

Or perhaps if you want it to remain as part of the repository, it could be a separate `INSTALL.md` file.

Also, there are a few things in the 'needed software' that aren't really required.
