### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Kongledyret** [HDInnovations/UNIT3D#279]
- UNIT3D Version: 1.6.5
- Laravel Version: #.#.#
- PHP Version: PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS )

- Database Driver & Version: 5.7.22

### Description:
Install works fine. But when I try to reach the site I get 403 forbidden with Nginx. 
2018/05/05 00:42:44 [error] 25497#25497: *59 directory index of "/var/www/html/build" is forbidden, client: <ip>, server: domain.com, request: "GET / HTTP/1.1", host: "domain.com"
### Steps To Reproduce:
-

### Possible Fix:
-

**Comment by HDVinnie** [comment]
Few questions:

1) Why are you not using latest UNIT3D v1.7?

2) I assume you mean 403 Forbidden and not 404 Forbidden?

3) What does you NGINX config look like? `sudo nano /etc/nginx/sites-available/default`

**Comment by Kongledyret** [comment]
1 - I just git cloned the latest one. 
2 - Yes that is correct. 
3:  Nginx conf - https://www.pastiebin.com/5aed02bb19749

**Comment by poppabear8883** [comment]
permissions error likely on the `directory index of "/var/www/html/build" ` Check your permissions on the `html` and `build` directory ?

Also, i am assuming the `build` directory is your project root ?

The document root needs to point to the `public` directory in the project root

**Comment by HDVinnie** [comment]
is `/var/www/html/public` the actual directory of where UNIT3D is on your server? As the error you posted says irectory index of `/var/www/html/build` is forbidden. But your config is pointing to `\var/www/html/public`.

**Comment by Kongledyret** [comment]
Yes! The base directory of UNIT3D is /var/www/html/public as the config is stating. 

The public directory has been chown to www-data.

**Comment by HDVinnie** [comment]
Why does it say `build` in your error then? cd into the project root and run `sudo chown -R www-data: storage bootstrap public config` and `sudo find . -type d -exec chmod 0755 '{}' + -or -type f -exec chmod 0644 '{}' +` also `sudo systemctl reload nginx`.

**Comment by Kongledyret** [comment]
Hi,
The build error was me testing something. But the correct folder is public as the readme suggested. 
I did the mentioned command and got the following error in the log:
"2018/05/05 01:15:29 [error] 25987#25987: *86 directory index of "/var/www/html/public/" is forbidden, client: <ip>, server: yakuna.co, request: "GET / HTTP/1.1", host: "yakuna.co""

**Comment by HDVinnie** [comment]
Are you 100% sure that the folder permissions are what they should be? 403 translates to forbidden meaning that somewhere in your config or permissions, it is disallowing access. This is not a UNIT3D issue but more so a server issue your end.

What if you cd into `/var/www/html/public/` and try running `sudo chmod -R 777 public`? Does it work if you do that? 

NOTE: `sudo chmod -R 777 public` is for test case only and should NOT stay that way.

**Comment by Kongledyret** [comment]
Yea. I've tried the command and it did not do any changes tbh.

**Comment by HDVinnie** [comment]
Im not sure then sorry. All I can say is it is a server issue and not UNIT3D related.

**Comment by Kongledyret** [comment]
Yea. Like mentioned in pm I'll try with another server later on. 
Feel free to leave this issue open for confirmation or close it if needed. 

Cheers.

**Comment by Kongledyret** [comment]
Hi! 
I've managed to get the site up with the index page. But other links such as browse, staff_dashboard etc is not found.

**Comment by HDVinnie** [comment]
Unable to replicate
