### ISSUE TITLE
TheSportsDB support

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#289]
Hi,

obviously the tracker is made for TV and Movies, but apparently there is a sportsdb site which could scrape data for sport events too.

https://www.thesportsdb.com

Would be nice to see it in at some point, unless you got something better for non-tv/movie related torrents

**Comment by HDVinnie** [comment]
We have decided this will not be added to core. This API is not the best and UNIT3D is aimed for movies and tv.
