### ISSUE TITLE
Registration with special characters not possible/wrong error message

### ISSUE THREAD

**Issue by project-online** [HDInnovations/UNIT3D#294]
- UNIT3D Version: 1.7
- Laravel Version: 5.5
- PHP Version:
- Database Driver & Version:

### Description:
If I try to register a username with a special character (only "$" tested) I get a wrong error message, if special characters are not allowed.

### Steps To Reproduce:
1. Cllick on SIGNUP
2. Enter username with a "$" in it, enter email and password and click on SIGNUP
3. The following message appear at top right "Whoops! Either The Username/Email is already in use or you missed a field. Make sure password is also min 6 charaters long.

### Possible Fix:
If special characters are not allowd, add this to the message or make the message more specific.
Also the word "character" in the error message has a typo.

**Comment by HDVinnie** [comment]
Ill fix the message tomorrow to be more specific. But yes only `alpha_dash` is allowed for usernames.
