### ISSUE TITLE
Upload achievement stats

### ISSUE THREAD

**Issue by Rukus308** [HDInnovations/UNIT3D#299]
Hello, Yesterday I noticed an indifference between upload counts on the achievements page vs upload counts on the profile page, for example the achievement "You have made 25 torrent uploads!" shows a "23/25" count however the profile page shows a "Total uploads : 33" (Which is correct). I tried to think logically what might have caused this indifference and it dawned on me that the first lot of uploads were done with the "Anonymous" option ticked and the remaining were public, afterwards the previous were then edited back to public also ("Anonymous" option unticked on torrent page).

I can't remember the exact count of uploads before they were then posted public but it does appears the "Anonymous" option may have affected the count on the achievements page.

Am I miss-understanding anything, is that expected behavior or possibly a quirk in the system to hammer out? I slightly assume that "Anonymous" or not it would still count on the achievements page.

Thanks in advance!

**Comment by HDVinnie** [comment]
It is indeed the case that Anonymous uploads don't count towards achievements.
```
$anon = $torrent->anon;

        if ($anon == 0) {
            // Auto Shout and Achievements
            $user->unlock(new UserMadeUpload(), 1);
            $user->addProgress(new UserMade25Uploads(), 1);
            $user->addProgress(new UserMade50Uploads(), 1);
            $user->addProgress(new UserMade100Uploads(), 1);
            $user->addProgress(new UserMade200Uploads(), 1);
            $user->addProgress(new UserMade300Uploads(), 1);
            $user->addProgress(new UserMade400Uploads(), 1);
            $user->addProgress(new UserMade500Uploads(), 1);
            $user->addProgress(new UserMade600Uploads(), 1);
            $user->addProgress(new UserMade700Uploads(), 1);
            $user->addProgress(new UserMade800Uploads(), 1);
            $user->addProgress(new UserMade900Uploads(), 1);
        }
```

The main reason behind this was because if you do all your uploads anon but your profile is not set to private then people will be able to see your recent achievements which might just include a for example  `UserMade600Uploads` badge thus blowing up your spot....

**Comment by Rukus308** [comment]
Thanks Vinnie, that makes sense, was slightly hoping that changing a torrent from anon back to public would correct that count but I see it happens at the torrent add phase so all good, its then too late after the fact. Cheers for the info 👍

**Comment by HDVinnie** [comment]
Yes, achievements/autoshouts/notification/ect all happen at the upload/moderation stage.
