### ISSUE TITLE
Autogrouping issues

### ISSUE THREAD

**Issue by theunrealPikachu** [HDInnovations/UNIT3D#340]
### Description:
BluMaster >= 5TB but < 20TB and account 1 month old
BluExtremist >= 20TB but < 50TB and account 3 month old

if you uploaded more than 20TB in less than 3 months user wont be eligible for any of the above mentioned rank making the user instead of BluMaster

this is true for all other ranks as well 
for eg 
BluExtremist >= 20TB but < 50TB and account 3 month old
BluLegend >= 50TB but < 100TB and account 6 month old

also 
if a user is more than 3 months old but have uploaded more than 100TB user should be bluExtremist but wont be assigned since theres an upperlimit

For bluseeder
            if ($user->getSeeding() >= 150 && round($user->getTotalSeedTime() / max(1, $hiscount)) > 2592000 **&& $user->created_at < $current->copy()->subDays(30)->toDateTimeString()** && $user->group_id != 17) 

checking for average seedtime as well as account older than 30days seems redundant since user can't get 30days avg seedtime in less than 30 days 
note!! i didn't take into account that someone seeding from more than one machine and their seddtime adding up then it should be doable 

### Possible Fix:

Remove upperlimit for all ranks

**Comment by HDVinnie** [comment]
That will not work. There is a reason in the upper limits parking place. Eventually the automated part of the group systems will be re-written

**Comment by theunrealPikachu** [comment]
This is just food for thought 
this should remove need for parking place??(genuine question, I am assuming we need upper limits so it does not execute every if statement)


what if we switch the order 

current order
leech > member > blumember > blumaster etc

to

leech > member > blutopian > bluLegend > bluextremist
