### ISSUE TITLE
Can´t start unit3d-socket-io

### ISSUE THREAD

**Issue by GETuP80** [HDInnovations/UNIT3D#345]
- UNIT3D Version: 1.8
- Laravel Version: 5.6.26
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7.22

### Description:

Hello,

the title says everything i can´t start the socket.io!

It stops here: 

`unit3d-queue:unit3d-queue_00            RUNNING   pid 1847, uptime 0:00:10`
`unit3d-queue:unit3d-queue_01            RUNNING   pid 1846, uptime 0:00:10`
`unit3d-socket-io:unit3d-socket-io_00   BACKOFF   Exited too quickly (process log may have details)`

When i run (for test) : 

`laravel-echo-server start` 

I get the following error: 

`{ Error: EISDIR: illegal operation on a directory, read`
`    at Object.fs.readSync (fs.js:675:18)`
`    at tryReadSync (fs.js:540:20)`
`    at Object.fs.readFileSync (fs.js:583:19)`
`    at /usr/lib/node_modules/laravel-echo-server/dist/server.js:44:26`
`    at new Promise (<anonymous>)`
`    at Server.secure (/usr/lib/node_modules/laravel-echo-server/dist/server.js:39:16)`
`    at /usr/lib/node_modules/laravel-echo-server/dist/server.js:28:23`
`    at new Promise (<anonymous>)`
`    at Server.serverProtocol (/usr/lib/node_modules/laravel-echo-server/dist/server.js:26:16)`
`    at /usr/lib/node_modules/laravel-echo-server/dist/server.js:17:19`
`    at new Promise (<anonymous>)`
`    at Server.init (/usr/lib/node_modules/laravel-echo-server/dist/server.js:16:16)`
`    at /usr/lib/node_modules/laravel-echo-server/dist/echo-server.js:45:26`
`    at new Promise (<anonymous>)`
`    at EchoServer.run (/usr/lib/node_modules/laravel-echo-server/dist/echo-server.js:41:16)`
`    at /usr/lib/node_modules/laravel-echo-server/dist/cli/cli.js:156:18 errno: -21, code: 'EISDIR', syscall:` `'read' }`

Maybe anyone had the same issue and would help me?

Greets 

GETuP80

**Comment by HDVinnie** [comment]
What OS are you running?

**Comment by GETuP80** [comment]
Hi,
i installed Ubuntu 16.04.4 LTS

**Comment by HDVinnie** [comment]
You doing the install as root? Or a sudo user with proper permissions?

**Comment by GETuP80** [comment]
as root and as a sudo user ... it is the same

**Comment by HDVinnie** [comment]
Ok I am just using a example here.  

1) SSH into your server as root.

2) cd into main directory of codebase
`cd /var/www/html/`

3) Remove node_modules
`rm -rf node_modules`

4) Reinstall 
`composer install && composer require predis/predis && npm install && npm install --save-dev socket.io-client && npm run prod`

5) Permissions
`sudo chown -R www-data: storage bootstrap public config`

6) Test
`laravel-echo-server start`

Report back......this is assuming you went threw whole installation but could get socket.io to work.

**Comment by GETuP80** [comment]
ok i got three errors but the same output as before when i run `laravel-echo-server start`

error one and two:

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

this i can install with:

`npm -i install -f`

the third error is:

`[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".`

when run:

`npm run prod`

**Comment by HDVinnie** [comment]
Yeah I'm not sure. I just installed UNIT3D today for a fellow with no issues. 

If you want me to try and install for you feel free to email me at unit3d@protonmail.com

**Comment by HDVinnie** [comment]
Closing this since I was able to install on your VPS with no issues by following the README to a T. Im assuming you just messed up somewhere.

```
root@vps*******:/var/www/html# sudo supervisorctl
unit3d-queue:unit3d-queue_00           RUNNING   pid 11517, uptime 0:00:08
unit3d-queue:unit3d-queue_01           RUNNING   pid 11516, uptime 0:00:08
unit3d-socket-io:unit3d-socket-io_00   RUNNING   pid 11515, uptime 0:00:08
```

**Comment by GETuP80** [comment]
Hi and BIG THX for your Help!!!

The Error is easy and stupid of me!

U recommended nginx but i´m a lover of apache and i don´t configure my vhost correct ...

Missing lines:

`<FilesMatch \.php$>`
`SetHandler "proxy:unix:/var/run/php/php7.2-fpm.sock|fcgi://localhost/"`
`</FilesMatch>`

Now everything works fine!

Greets 

GETuP80

**Comment by HDVinnie** [comment]
Glad you sorted it out for APACHE.
