### ISSUE TITLE
Replying to a PM in your outbox sends a message to yourself instead of the recipient

### ISSUE THREAD

**Issue by werrpy** [HDInnovations/UNIT3D#347]
Replying to a PM in your outbox sends a message to yourself instead of the recipient.

**Comment by VerioPL** [comment]
Fixed in (https://github.com/HDInnovations/UNIT3D/commit/41b8ee3c53b64a98012d663ff4b707081c4dd950#diff-648949aa7518d76e8a3064ead9a3ef40) by @HDVinnie
