### ISSUE TITLE
Forum fixes

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#358]
I know you are working on it, but I'd like to be notified about updates in that regard, hence the issue.

What I am talking about is:
forum creation
category creation
add function to quote button
fix permission issues
add ability to change permissions (it's there, but gives a 500 error on the backend, as you know)

keep up the great work

**Comment by HDVinnie** [comment]
I believe @poppabear8883 plans are to still complete his rewrite branch of Forums 2.0

**Comment by poppabear8883** [comment]
@xR4E `quote button` was added some time ago and also tagging users with `@username` and Yes i am still working on an entire re-write of the forums system.

**Comment by HDVinnie** [comment]
@xR4E see d16d76c8b9dbafb7ad907500e9ac180d881fd844
