### ISSUE TITLE
Mail server

### ISSUE THREAD

**Issue by JohnyBeGood** [HDInnovations/UNIT3D#371]
Hello,

I'm testing and I opened it for new registration but when I sign up as new user it sends email to confirm.
This being new server I'm not even sure if email is installed/setup. What was intention of email section when setting up? to use local mail server or external ie. gmail?

**Comment by HDVinnie** [comment]
The intention is to use a external mail server like torguard or gmail. 
https://torguard.net/anonymous-email.php

Once you have your mail settings in your `.env` you can fire off a test email to make sure there right. `php artisan clear:all` and then `php artisan test:email`

**Comment by JohnyBeGood** [comment]
I was able to configure Gmail and here are the settings that worked and test email was sent out successfully:

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=mygmail@gmail.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=TLS
MAIL_FROM_NAME=TestSite.Com
MAIL_FROM_ADDRESS=mygmail@gmail.com 
```
Now when new user registers they never get email to confirm. How can I troubleshoot it?

**Comment by HDVinnie** [comment]
run `sudo supervisorctl reload` and then `sudo supervisorctl  status`. Make sure everything says running. @poppabear8883 will need to add `sudo supervisorctl reload` to the installer here https://github.com/ServNX/UNIT3D-INSTALLER/blob/7287fa9404614a2dec45c554ea87ae3f20ba2cfe/src/Installer/UNIT3D/Unit3dSetup.php#L127

If solves your issue please report back so issue can be closed.

**Comment by JohnyBeGood** [comment]
Thanks! As soon as I ran `sudo supervisorctl reload` registered user got email right away.
```
user@bt:~$ sudo supervisorctl reload
Restarted supervisord
user@bt:~$ sudo supervisorctl status
unit3d-chat-server:unit3d-chat-server_00   RUNNING   pid 1797, uptime 0:00:04
unit3d-queue:unit3d-queue_00               RUNNING   pid 1799, uptime 0:00:04
unit3d-queue:unit3d-queue_01               RUNNING   pid 1798, uptime 0:00:04
user@bt:~$

```
