### ISSUE TITLE
How to enable SSL after install?

### ISSUE THREAD

**Issue by JohnyBeGood** [HDInnovations/UNIT3D#373]
Hello,

When I was using installer I've selected no when asked about "Enable SSL (https)". Now I would like to work on getting https enabled. Is this https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04  the first step?

**Comment by HDVinnie** [comment]
1) Yes. Follow that guide.
NOTE: Make sure when you see **Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.**
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.

Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
**YOU SELECT 2**


2) run `sudo ufw allow 6001` and then `sudo ufw enable` to make sure its running.

3) Then you will need to redo Laravel Echo configuration. run ` nano laravel-echo-server.json`

You should see something like
```
{
        "authHost": "yourdomain.com",
        "authEndpoint": "/broadcasting/auth",
        "clients": [
                {
                        "appId": "************",
                        "key": "*********************************"
                }
        ],
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": "yourdomain.com",
        "port": "6001",
"protocol": "http",
        "socketio": {},
        "sslCertPath": "",
        "sslKeyPath": "",
        "sslCertChainPath": "",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": false,
                "allowOrigin": "",
                "allowMethods": "",
                "allowHeaders": ""
        }
}
```

MAKE IT LOOK LIKE THIS

```
{
        "authHost": "https://yourdomain.com",
        "authEndpoint": "/broadcasting/auth",
        "clients": [
                {
                        "appId": "**********",
                        "key": "**************************"
                }
        ],
        "database": "redis",
        "databaseConfig": {
                "redis": {},
                "sqlite": {
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }
        },
        "devMode": false,
        "host": "yourdomain.com",
        "port": "6001",
"protocol": "https",
        "socketio": {},
        "sslCertPath": "/etc/letsencrypt/live/yourdomain.com/cert.pem",
        "sslKeyPath": "/etc/letsencrypt/live/yourdomain.com/privkey.pem",
        "sslCertChainPath": "/etc/letsencrypt/live/yourdomain.com/fullchain.pem",
        "sslPassphrase": "",
        "apiOriginAllow": {
                "allowCors": false,
                "allowOrigin": "",
                "allowMethods": "",
                "allowHeaders": ""
        }
}
```

SAVE AND EXIT

4) run `sudo chown www-data /etc/letsencrypt -R`

5) run `sudo supervisorctl reload`

Then should be good....make sure site and chat works. Make sure trying to access `http://mydomain.com` redirects to `https://mydomain.com`

**Comment by HDVinnie** [comment]
O and in the future don't ever not make a site HTTPS when LetsEncrypt makes it so easy and free. We plan to remove the option to not use HTTPS all together from the installer.

**Comment by poppabear8883** [comment]
Ref: https://github.com/ServNX/UNIT3D-INSTALLER/issues/14

**Comment by JohnyBeGood** [comment]
Thank you! I got it to work and I know I should've enabled HTTPS from the start but was afraid it would not work and would prevent me from using the site.
One part that was confusing here https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04  **Step 2 — Confirming Nginx's Configuration** where it said `sudo nano /etc/nginx/sites-available/example.com` it should actually be `sudo nano /etc/nginx/sites-available/default`
Everything else what HDVinnie suggested worked!
