### ISSUE TITLE
Quick Search not searching

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#379]
When trying to utilize quick search it only brings up the default torrent list. it does not filter.

### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.8.5

-- Laravel Version: 5.6.33

-- PHP Version: 7.2.8

-- Database Driver & Version: MySql Ver 14.14 Distrib 5.7.23

-- Web Server Driver & Version: Nginx 1.15.0

-- OS Driver and Version: Ubuntu 18.04.1 LTS

### Expected Behavior:

Search/Filter torrent list

### Actual Behavior:

Just opens torrent list

### Steps To Reproduce The Problem:

Type in quick search and press enter

### Possible Fix:
?

**Comment by HDVinnie** [comment]
Quick search was removed in latest release as it does not work with new faceted search system. It will be added back in a new way down the road.
