### ISSUE TITLE
Add list of active users to chat

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#382]
### Issue Type
- [x] Feature Idea

Requesting chat box incorporate a list of active users in a right side panel. Maybe have the active users panel minimize and expand?

**Comment by HDVinnie** [comment]
I believe its on the roadmap. Not sure where @poppabear8883 stands with the chat system. I do recall the idea was to add a tabs system to it for Private Chatting and Online Users Tab.

https://i.gyazo.com/c8e351d6ecf60b800e855306cfea1a50.gif

**Comment by poppabear8883** [comment]
It is 90% ready, There are some complications with the events which has pushed me off of it for now. I plan to have it finished up sooner than later.

**Comment by HDVinnie** [comment]
This was added in UNIT3D v1.9
