### ISSUE TITLE
Staff only forum not possible

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#385]
Hi,

I tried to have a staff-only forum and it kinda works, but it will show the chat entry and the post excerpts on the front page anyway, so nothing "confidential" can be posted there.

**Comment by yourguessismine** [comment]
Try creating a staff only category. This is what I have done and recent topics and posts are not viewable on the homepage to non staff

**Comment by HDVinnie** [comment]
@xR4E the staff only forum must be within a staff only category as @yourguessismine has pointed out.  I cannot replicate your issue besides the chat announcements which we are already aware of.

**Comment by HDVinnie** [comment]
Haven't heard back in 30 days @xR4E . Issue now closed.
