### ISSUE TITLE
Forum Suggestions

### ISSUE THREAD

**Issue by HVRVKVT** [HDInnovations/UNIT3D#398]
### Issue Type
- [x] Feature Idea
- [x] Enhancement

### Forum Enhancements

• When voting & editing a post in the forum, site refreshes and redirects to the first post in the thread. Instead refresh to the permalink of the specific post.
**DONE**

• Let OP (of any rank) label a thread as solved

• Ability to tip a post with bon

• Search into [posts ](https://blutopia.xyz/forums/topic/search-forum-by-postcontent.999)
  • Filter searches by label, subforum

• Ability to subscribe to a subforum
  • Overview of posts from subscribed threads, and subforums

**Comment by HDVinnie** [comment]
Closed in #517
