### ISSUE TITLE
Report request produces error

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#402]
Pressing "Report request" on request page opens modal, clicking "Report request" within the modal produces 500 error (see below).

`Trying to get property 'user' of non-object {"userId":3,"email":"email@domain.tld","exception":"[object] (ErrorException(code: 0): Trying to get property 'user' of non-object at /var/www/html/app/Http/Controllers/ReportController.php:49)`

### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.37

-- PHP Version: 7.2.9

-- Database Driver & Version: MySQL 5.7.23

-- Web Server Driver & Version: nginx 1.15.0

-- OS Driver and Version: Ubuntu 18.04.1

### Expected Behavior: 

Submit report and toater message displayed.

### Actual Behavior: 

500 error

### Steps To Reproduce The Problem:
1. Open a request
2. Click Report request at the top of the page
3. Click Report request within modal.

### Possible Fix:
Assign alternate value to `$reported_user` variable within the ReportController so if `$torrent->user` is not available it will use `torrentRequest->user`. I believe a new Requests class would need to be created.

**Comment by VerioPL** [comment]
Needed refactor postReport function
- input() directive
- validation
- rebuild syntax

Assigned to me
