### ISSUE TITLE
Sub forums do not sort by position

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#403]
Sub forums do not sort by given position. Looks like they are currently sorting by id, the order in which created.

### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.37

-- PHP Version: 7.2.9

-- Database Driver & Version: MySQL 5.7.23

-- Web Server Driver & Version: nginx 1.15.0

-- OS Driver and Version: Ubuntu 18.04.1

### Expected Behavior:

When assigning a new sub forum a position # it will go up or down the list accordingly.

### Actual Behavior:

Stays at the bottom of assigned category.

### Steps To Reproduce The Problem:
1. Create a new/edit a sub forum.
2. Assign a position other than last
3. Save/Submit

### Possible Fix:
?

**Comment by HVRVKVT** [comment]
IMO sorting alphabetically would be optimal

**Comment by yourguessismine** [comment]
Well sorting by assigned position gives you the freedom to do that or any other order one prefers.
