### ISSUE TITLE
Delete ChatBot

### ISSUE THREAD

**Issue by torrentocarlo** [HDInnovations/UNIT3D#405]
### Issue Type

- [x] Question

### End User Info
-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.38

Hi there,

Is it possible to delete the chat bot and it statistics ?

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D/commit/6bc05ff948006f7c697620608414be35ccced214
