### ISSUE TITLE
Forum bugs

### ISSUE THREAD

**Issue by torrentocarlo** [HDInnovations/UNIT3D#411]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.8.6

Hi there,

I found some bugs in the forum section.

First, the read/unread function doesn't work.
Second, when we subscribe to a topic, we doesn't receive notifications when this topic is update.

**Comment by HDVinnie** [comment]
These are not bugs...

> First, the read/unread function doesn't work.

There is no read/unread function.....never was. Not sure why you think there is. 

> Second, when we subscribe to a topic, we doesn't receive notifications when this topic is update.

This is also not a bug. It was not designed to function like that. It simply notifies the subscriber when there is a new post on said topic.

You are more then welcome to open two SEPARATE issues for these with the enhancement/feature tag.
