### ISSUE TITLE
Laravel error during backup

### ISSUE THREAD

**Issue by MyAlien** [HDInnovations/UNIT3D#413]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.37

-- PHP Version:7.2.10

-- Database Driver & Version:5.7.23

Can not create a backup from the Staff Dashboard.
I'm never used this option
Laravel Logs errors 
`Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 36 {"userId":5,"email":"email@protonmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Spatie\\DbDumper\\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 36 at /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php:115)`

**Comment by HDVinnie** [comment]
You may have used the installer before bug was fixed here.

https://github.com/poppabear8883/UNIT3D-INSTALLER/commit/f245e9c0d9e4693fe2d164f0f6369941cef8aca3

Please check your `.env` and make sure `DB_PORT` is set to `3306` and then run `php artisan clear:all`

**Comment by MyAlien** [comment]
Thank you very much.
Resolved
