### ISSUE TITLE
Add Featured Torrents

### ISSUE THREAD

**Issue by MyAlien** [HDInnovations/UNIT3D#415]
### Issue Type
- [x] Question

### End User Info
-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.37

-- PHP Version:7.2.10

-- Database Driver & Version:5.7.23

Hello,
I do not find how to add Featured Torrents, below the chatbox

**Comment by HDVinnie** [comment]
1) Go to a torrent.
2) On that page you will see `Staff Tools` row.
3) Click last button that says `Feature`.
4) Done.
