### ISSUE TITLE
Change Port WebSocket

### ISSUE THREAD

**Issue by MyAlien** [HDInnovations/UNIT3D#416]
### Issue Type
- [x] Question

### End User Info

-- UNIT3D Version: 1.8.6

-- Laravel Version: 5.6.37

-- PHP Version:7.2.10

-- Database Driver & Version:5.7.23

Hello,
To change the websocket port, the chat 0 users connected bugs.
Cloudflare not support all https ports.
Use port 8443

Here are my changes.
Does not work
`Edit /var/www/html/laravel-echo-server.json chnage port "port": "8443",
sudo ufw allow 8443/tcp
sudo supervisorctl reread && supervisorctl update && supervisorctl reload
php artisan cache:clear`

Thx ;)

**Comment by HDVinnie** [comment]
1) Edit `/laravel-echo-server.json` and change port.

2) change it in `resources/assets/js/bootstrap.js` as well
https://github.com/HDInnovations/UNIT3D/blob/master/resources/assets/js/bootstrap.js#L60

3) `sudo ufw allow 8443`

4) `sudo supervisorctl reread && supervisorctl update && supervisorctl reload`

5) `npm run prod`

6) `php artisan clear:all`

Outside that I cannot help you with your cloudfare issues as you have been told many many times.

**Comment by MyAlien** [comment]
Yes thanks .
Not just for UNIT3D

**Comment by HDVinnie** [comment]
Work for you?
