### ISSUE TITLE
Retro hit n runs after demoting user from immune group

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#417]
### Issue Type
- [x] Enhancement

Currently if a user is demoted from an immune group, all downloads not seeded for 7 days while in said immune group hit the users account all at once. It would be nice if all downloads while immune were exempt from the hit n run equation if/when a user is demoted to a non immune group.

**Comment by HDVinnie** [comment]
This was closed in commit 619d83098b08233ffe8647fafbe46525bf28acf7
