### ISSUE TITLE
Seed cannot be downloaded

### ISSUE THREAD

**Issue by LALADevil** [HDInnovations/UNIT3D#421]
### Issue Type
- [x] Question

Hello

I made a seed and planted it normally:

![lala im_2018-10-15_21-57-32](https://user-images.githubusercontent.com/33951857/46955403-71bac380-d0c5-11e8-81e1-e2a33b6b3372.png)

I can see the same information on the website:

![lala im_2018-10-15_21-59-00](https://user-images.githubusercontent.com/33951857/46955515-ae86ba80-d0c5-11e8-9b91-8a131a854f7f.png)

But I can't download it using any client, like DelugeWEBUI:

![lala im_2018-10-15_22-02-16](https://user-images.githubusercontent.com/33951857/46955651-01f90880-d0c6-11e8-909d-18c484eb6d85.png)

qBittorrent:

![lala im_2018-10-15_22-03-45](https://user-images.githubusercontent.com/33951857/46955729-38cf1e80-d0c6-11e8-939e-4bb46d5994cd.png)

I closed SELinux and Firewalld.

Any possible suggestions? Thank you

### End User Info
-- UNIT3D Version: v1.8.6
-- PHP Version:7.2.4
-- Database Driver & Version:MySQL 5.7.19
-- Web Server Driver & Version:Nginx1.14.0
-- OS Driver and Version: CentOS7.5

**Comment by HDVinnie** [comment]
This has nothing to do with UNIT3D really. This is basic peering. 

The site tracker (announce) has nothing to do with speeds/connectivity. Torrents are peer to peer. The tracker(announce) merely passes a client a list of peers and the rest of it is down to their respective clients to contact each other and start sharing data.

Are you trying to download from yourself? Have you had some friends upload something to your site and download from them or have them download from you?

I can assure you there is nothing wrong with UNIT3D's (Tracker / Announce Code).

**Comment by LALADevil** [comment]
I can send you an invitation to register, can you help me test it? Thank you

**Comment by HDVinnie** [comment]
Again this is a connectivity issue your end. You can easily test this by doing the following. 

1) Invite 5-10 friends to your site.

2) Upload a torrent.

3) Have those 5-10 friends try to download it from you.

4) Have one of your 5-10 friends upload a torrent.

5) You can your other friends try to then download from that uploader.

**Comment by HDVinnie** [comment]
Sure you can send me a invite to unit3d@protonmail.com

**Comment by HDVinnie** [comment]
Also join Discord so we can discuss this further. Closing this issue since it is not a issue with the codebase.

https://discord.gg/g3w5C3w

**Comment by LALADevil** [comment]
I will send you an invitation, please check
