### ISSUE TITLE
All Contributors

### ISSUE THREAD

**Issue by MatheusRV** [HDInnovations/UNIT3D#426]
### Issue Type
- [X] Enhancement

I believe that a good way to value project developers is to use https://github.com/kentcdodds/all-contributors that allows all employees to be rewarded for any task they may perform. What do you think? Can we implement this here?

**Comment by HDVinnie** [comment]
Looks neat. I got no issue with it. I will look int the repo and how it works.

**Comment by HDVinnie** [comment]
Done
