### ISSUE TITLE
A few new ideas -[ ] Feature Idea

### ISSUE THREAD

**Issue by GouroB19** [HDInnovations/UNIT3D#429]
#Hi guys, I have a few idea's/request ... I believe they will be valuable in time 

1. Support system. I'm given to understand we have Bug report in UNIT3D, and there's forum but I think every tracker should have its own support ticket system. Because there are many topics and issues we would rather discuss with the concerned user 1to1 than letting the entire community read it. 

2. Top Banner. I guess it will look much prettier if we could add a small banner where the home link shows or at the very top. Nothing fancy or big ... just something to distinguish every individual UNIT3D site's from each other. 

3. Deeper user searching option. In member's section, search can be done only by user names, but i think it will be more helpful if we could search by groups aswell. To keep count of specific group and class. A search option with email address will help in long run aswell. 

4.  An option in forum to hold Application for staff and contributor. So we can create staff Application, appointments and keep a record of all these in the same script. 

5. This one is a different kind of idea, its not only gonna play for the trackers uses your script but the core developers too. If you can add a built in donation system that works like 

When a user donates to say DXD $10. It will be processed and paid to UNIT3D's patroen or bitcoin or whichever other ways are there, and UNIT3D will release the fund's once or twice a month after it cuts a certain % for being the root of it. 
I understand its a free license and no one is bound to pay, even a penny if they dont want to. But you can always make this particular option " Donation system " as an optional addon. Whoever wants it ON, accepts the terms. That way, it will not just benefit the tracker runs it, but also helps and motivated the core dev's. 

6. This idea is a bit vast and im hoping you guys will consider this for the next big update, V.2. 
Its about a more vivid and expandable user group permission and over all a bit more customizable tracker & forum permission's. Something vBulletin or phpBB uses. It makes life a hell lot easier. Any particular user can be granted or removed from particular access while keeping him in a group that has more or less access. 

i.e: userX belongs to group Moderator, but his default accesses can be changed individually. Like he can be added mod only for 4 selected forums and he can only approve torrents. This sounds tricky i know but i sincerely believe this will make UNIT3D a more sure choice for a lot more people. 

7. Top Uploader list on home page. This is highly motivating, please consider this. 

8. Bon store option: If you can add 2 more option in Bon store, it would be awesome. 
     - Purchase Username change with Seedbonus
     - Purchase custom things we have in Admin store using seedbonus. ( It can be a seedbox, a VPS or even gift cards ) This is just to get the users be competitive with each other. Plus this feature can be used when we host a upload race or uploading contest. 

9. A small BBcode storing option, so we can have our favorite BBCode decorations handy when uploading. We all have our own style to decorate torrents to make them look beautiful and distinctive.. so I guess it will be loved by many. 

 

### End User Info
-- UNIT3D Version: 1.8.7

-- Laravel Version: 5.3.69

-- PHP Version: 7.2.10-0ubuntu0.18.04.1

-- Database Driver & Version: 5.7.23-0ubuntu0.18.04.1

-- Web Server Driver & Version: NGNIX

-- OS Driver and Version: Ubuntu 18.04.1

**Comment by HDVinnie** [comment]
One topic per issue. You have 9 features/ideas/enhancements crammed into one issue.
