### ISSUE TITLE
Support System [features]

### ISSUE THREAD

**Issue by GouroB19** [HDInnovations/UNIT3D#430]
Support system. I'm given to understand we have Bug report in UNIT3D, and there's forum but I think every tracker should have its own support ticket system. Because there are many topics and issues we would rather discuss with the concerned user 1to1 than letting the entire community read it.

**Comment by HDVinnie** [comment]
Duplicate!

https://github.com/HDInnovations/UNIT3D/issues/431
https://github.com/HDInnovations/UNIT3D/tree/Support/Helpdesk-System
