### ISSUE TITLE
Deeper user search [Feature-request]

### ISSUE THREAD

**Issue by GouroB19** [HDInnovations/UNIT3D#431]
Deeper user searching option. In member's section, search can be done only by user names, but i think it will be more helpful if we could search by groups aswell. To keep count of specific group and class. A search option with email address will help in long run aswell.

**Comment by HDVinnie** [comment]
You can already see `count of specific group and class` on extra stats page under groups. I don't think this is something that should be added to the core. Basic username search is good enough for member use.
