### ISSUE TITLE
[Feature Idea] - Donation system

### ISSUE THREAD

**Issue by GouroB19** [HDInnovations/UNIT3D#432]
This one is a different kind of idea, its not only gonna play for the trackers uses your script but the core developers too. If you can add a built in donation system that works like

When a user donates to say DXD $10. It will be processed and paid to UNIT3D's patroen or bitcoin or whichever other ways are there, and UNIT3D will release the fund's once or twice a month after it cuts a certain % for being the root of it.
I understand its a free license and no one is bound to pay, even a penny if they dont want to. But you can always make this particular option " Donation system " as an optional addon. Whoever wants it ON, accepts the terms. That way, it will not just benefit the tracker runs it, but also helps and motivated the core dev's.

**Comment by HDVinnie** [comment]
Duplicate!

https://github.com/HDInnovations/UNIT3D/issues/80
