### ISSUE TITLE
[Feature-request]-user/group permission

### ISSUE THREAD

**Issue by GouroB19** [HDInnovations/UNIT3D#433]
This idea is a bit vast and im hoping you guys will consider this for the next big update, V.2.
Its about a more vivid and expandable user group permission and over all a bit more customizable tracker & forum permission's. Something vBulletin or phpBB uses. It makes life a hell lot easier. Any particular user can be granted or removed from particular access while keeping him in a group that has more or less access.
i.e: userX belongs to group Moderator, but his default accesses can be changed individually. Like he can be added mod only for 4 selected forums and he can only approve torrents. This sounds tricky i know but i sincerely believe this will make UNIT3D a more sure choice for a lot more people.

**Comment by HDVinnie** [comment]
Duplicate!

https://github.com/HDInnovations/UNIT3D/issues/284
