### ISSUE TITLE
Question about UNIT3D

### ISSUE THREAD

**Issue by mcangeli** [HDInnovations/UNIT3D#441]
### Issue Type
- [x] Question

Ok, so this is a pretty simple question and is kind of a fact finding mission...

I run linuxtracker.org and I am looking for a possible replacement for my severely outdated xbtit install (thats fairly custom at this point). 

The site is open (no registrations required for downloading) as we're serving torrents for Linux Distributions, but it requires an account for uploading files to the site and for some of the other features.

Is it possible with UNIT3D to have the site setup that way? With an open frontend for downloading the torrents but limit other access to stuff on the site to registered members?

**Comment by mcangeli** [comment]
Ok. yea, the viewing and downloading the torrents would be the only thing guests would be able to do. I assume there's code involved to check and see if the user is logged in? Could that code be adapted so that if they weren't logged in it saw them as a specific user (create a "guest" user in the DB) and limit that guest user to a very tightened usergroup?

**Comment by HDVinnie** [comment]
Something along those lines yes. I can 100% be done. As I said though it will require some core code changes outside UNIT3D's default. If your interested and need the custom work done you can email me and I will get back to your as soon as possible to discuss it further. 

unit3d@protonmail.com

**Comment by zadika** [comment]
anyway to import other old tracker sources user databases?

i using actually the netvision v1 with round 800 users and want to switch source.
