### ISSUE TITLE
[Req] Mass e-mail 

### ISSUE THREAD

**Issue by DXDHD** [HDInnovations/UNIT3D#456]
### Issue Type
- [x] Feature Idea

### End User Info
-- UNIT3D Version: 1.8.8

-- Laravel Version: 5.7.13

-- PHP Version: 7.2.10-0ubuntu0.18.04.1

-- Database Driver & Version: 5.7.24-0 

-- Web Server Driver & Version: Ngnix

-- OS Driver and Version: Ubuntu0.18.04.1

### Steps To Reproduce The Problem:
1. N/A
2. N/A
3. N/A

**Comment by HDVinnie** [comment]
Users are already emailed regarding the user pruning system.

https://github.com/HDInnovations/UNIT3D/blob/master/config/pruning.php

https://github.com/HDInnovations/UNIT3D/blob/master/app/Console/Commands/AutoDisableInactiveUsers.php

https://github.com/HDInnovations/UNIT3D/blob/master/app/Console/Commands/AutoSoftDeleteDisabledUsers.php

https://github.com/HDInnovations/UNIT3D/blob/master/resources/views/emails/disabled.blade.php

https://github.com/HDInnovations/UNIT3D/blob/master/resources/views/emails/pruned.blade.php
