### ISSUE TITLE
Failed to open registration.

### ISSUE THREAD

**Issue by m333w** [HDInnovations/UNIT3D#460]
Hi, 

I am trying to open the registration on my tracker with `    'private' => false,`

But i got the error : 

`Whoops!
Open Reg Closed! You Must Be Invited To Register! You Have Been Redirected To Login Page!`

How i can solve this ?

Best regards.

**Comment by HDVinnie** [comment]
Your changing the wrong thing. set `'private' => false,`  back to `'private' => true,`.

In the same configuration file you will see right below it: ` 'invite-only' => true,`. Set it to `0` or `false`

I suggest you view the configs directly in the repo so can read the code comments and understand them.
https://github.com/HDInnovations/UNIT3D/blob/51dbce217ec7a695de82fde7dd3ccc867d145cdb/config/other.php#L125

Also for simple questions like this please use or Discord and not open issues.
https://discord.gg/AyCaSe

**Comment by m333w** [comment]
Oh sorry, works beter now ^^ 

Thx :)
