### ISSUE TITLE
Seedbox Add and Delete

### ISSUE THREAD

**Issue by togwar** [HDInnovations/UNIT3D#462]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#
Ver. 5.7.13
-- PHP Version:
php7.2.12-1+ubuntu16.04.1+deb.sury.org+1
-- Database Driver & Version:
5.7.24-0ubuntu0.16.04.1
-- Web Server Driver & Version:

-- OS Driver and Version:
Linux Ubuntu 16.04

### Steps To Reproduce The Problem:
1. Add a Seedbox IP
2. Delete a Seedbox IP
3. Try to Add a Seedbox IP again or for another User (Seedbox MultiUser)

### Possible Fix:
1 - Have to possible to register a same IP for multi-user "shared seedbox".
2 - IF Seedbox "MultiUser", When try to add a seedbox IP, not show for user "on my seedbox", if this has inserted on database for another user.
3 - When Delete Seedbox, clean a database for this user only.

**Comment by HDVinnie** [comment]
Im unable to replicate this. I can add a seedbox IP on demo site for UNIT3D account using IP 1.2.3.4

Then delete it.

Then readd it again no problem.

The IP address column is UNIQUE and thus should not allow multiple entries of same IP.
