### ISSUE TITLE
IDE-Helper Meta nesting level of '256'

### ISSUE THREAD

**Issue by tntsoft** [HDInnovations/UNIT3D#464]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: Latest (unit3d.php says codebase version 1.8.8)

-- Laravel Version: 2.0.1

-- PHP Version: 7.2.12

-- Database Driver & Version: MySQL 10.1.36-MariaDB

-- Web Server Driver & Version: Xampp 7.2.12

-- OS Driver and Version: Windows 10

### Expected Behavior:
Should construct a meta file to help with IDE auto complete.

### Actual Behavior:
php artisan ide-helper:meta
`Symfony\Component\Debug\Exception\FatalThrowableError  : Maximum function nesting level of '256' reached, aborting!

  at C:\xampp\htdocs\Tracker\vendor\laravel\framework\src\Illuminate\Container\Container.php: 745
  741:      * @return string|null
  742:      */
  743:     protected function findInContextualBindings($abstract)
  744:     {
  745:         if (isset($this->contextual[end($this->buildStack)][$abstract])) {
  746:             return $this->contextual[end($this->buildStack)][$abstract];
  747:         }
  748:     }
  749:
  750:     /**

  Exception trace:

  1   end([])
      C:\xampp\htdocs\Tracker\vendor\laravel\framework\src\Illuminate\Container\Container.php : 745

  2   Illuminate\Container\Container::findInContextualBindings("Infinety\Config\Repository")
      C:\xampp\htdocs\Tracker\vendor\laravel\framework\src\Illuminate\Container\Container.php : 719

  Please use the argument -v to see more details.`
   

### Steps To Reproduce The Problem:
1. composer require barryvdh/laravel-ide-helper
2. php artisan ide-helper:meta

### Possible Fix:
It's probably because of a @OneToMany or @ManyToMany DB relationship that goes in an infinite loop. I looked for the issue but couldn't find it, I'm asking for the teams help as you know the code base the best!

Thanks in advance.

**Comment by HDVinnie** [comment]
Maybe @poppabear8883 can chime in. I also cannot find a issue anywhere.

**Comment by tntsoft** [comment]
If you cannot replicate, could you please just attach the meta file you get from running the above command, please? It would help me out a lot. If @poppabear8883 cannot replicate as well, I'll close. 

Thank you!

**Comment by HDVinnie** [comment]
Heres the environment I'm running this on. Simple DEMO server.

### End User Info
-- UNIT3D Version: 1.8.8

-- Laravel Version: 5.7.14

-- PHP Version: 7.2.12

-- Database Driver & Version: MySQL 5.7.24

-- Web Server Driver & Version: nginx/1.15.6

-- OS Driver and Version: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-38-generic x86_64)


When I run `php artisan ide-helper:meta` I get the following error. Assuming this 2GB RAM server just isn't good enough.

```
root@ubuntu-s-2vcpu-4gb-sfo2-01:/var/www/html# php artisan ide-helper:meta

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 3527413760) (tried to allocate 262144 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 719

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 3527413760) (tried to allocate 262144 bytes) in Unknown on line 0
```

I do not see any meta file generated on server. Partial or not. Im assuming it outputs it to project root? I could be way off as I have never used this package.

**Comment by HDVinnie** [comment]
@tntsoft looking at your error though it looks like the error is in relation to the config manager package we use. You could temporarily uninstall it and run the command to see if solves?

`"infinety-es/config-manager": "^1.1",`

**Comment by tntsoft** [comment]
Even if I remove that requirement and run the command, it still outputs the same error.

For reference, I did:
composer remove infinety-es/config-manager
php artisan ide-helper:meta

**Comment by HDVinnie** [comment]
Stange....I plan to remove that package completely anyway and move the non default configs into the database with a persistent settings manager.

**Comment by MrG01** [comment]
Hi,

Could you please check what your "memory_limit" is, according to your php config?

According to my testing, there seems to be two issues at play:
1. The config manager as previously referenced, 
2. Amount of Ram php has access too.

Based on my testing, due to the vast number of classes that the command loops through, the amount of ram needed to run `php artisan ide-helper:meta` is around 1G. 

My tests involved running the commands in configurations of 2G, 1G and 512MB respectively, in which only the last configuration gave me `php fatal error: memory allocation` error.

Therefore I am of the opinion that you temporarily need to raise the limit to run this command.

**Comment by tntsoft** [comment]
> Hi,
> 
> Could you please check what your "memory_limit" is, according to your php config?
> 
> According to my testing, there seems to be two issues at play:
> 
> 1. The config manager as previously referenced,
> 2. Amount of Ram php has access too.
> 
> Based on my testing, due to the vast number of classes that the command loops through, the amount of ram needed to run `php artisan ide-helper:meta` is around 1G.
> 
> My tests involved running the commands in configurations of 2G, 1G and 512MB respectively, in which only the last configuration gave me `php fatal error: memory allocation` error.
> 
> Therefore I am of the opinion that you temporarily need to raise the limit to run this command.

It still won't work for me even if I up my memory_limit to 2 G and remove the above package. If you've succeeded, could you please attach a link with the file, as I don't need to actively create it all the time.

Thanks in advance.

**Comment by MrG01** [comment]
This is the PhpStorm meta file generated on 2018-12-05 19:23:38.
 
https://gist.github.com/MrG01/2e64462fa487b32fe807700261374441

**Comment by tntsoft** [comment]
Thank you @HDVinnie @MrG01 ! 5 stars! 👍 #Closed
