### ISSUE TITLE
Change the top navigation "rocket" icon

### ISSUE THREAD

**Issue by m333w** [HDInnovations/UNIT3D#474]
Hi all, 

How i can change the the default logo ? I mean the rocket logo.
Best regards.

**Comment by m333w** [comment]
Thank you very mutch, is a lot of change to put a personal logo ?

**Comment by artyuum** [comment]
To put a personal logo you must use the `<img>` element. To do so, replace the following line: 
```html
<i class="{{ config('other.font-awesome') }} fa-rocket" style="display: inline;"></i>
```
With this: 
```html
<img src="http://fa2png.io/media/icons/font-awesome/4-7-0/rocket/32/0/ffffff_none.png" alt="logo">
```
Where the `src` attribute is the path to your personal logo.

**Comment by m333w** [comment]
@artyuum do you think its a lot of work to have a login pahe like this ? https://codepen.io/frytyler/pen/EGdtg can i make a pull request ?
