### ISSUE TITLE
Query IGDB API for games

### ISSUE THREAD

**Issue by Titeuf49** [HDInnovations/UNIT3D#475]
### Issue Type
- [x] Feature Idea

Hello,
can you add for IGDB.com's API games?
For more information :
https://api.igdb.com/
and
https://www.igdb.com/api
in advance thanks and happy holidays

**Comment by Titeuf49** [comment]
Hello HDVinnie,
I am happy to hear this news.
thank you for all your work!
and with a little advance cheerful and happy year 2019
Regards,
Titeuf

**Comment by Titeuf49** [comment]
Hi HDVinnie, 
did you implement the IGDB.com API?
Because I do not see it,
Thank you for your reply,
Warmest regards

**Comment by HDVinnie** [comment]
No it has been delayed.

**Comment by Titeuf49** [comment]
Hello HDVinnie,
Ok I hope you implement this API!
thank you

**Comment by HDVinnie** [comment]
@Titeuf49 few days out

[![Screen-Shot-2019-07-24-at-7-06-42-PM.png](https://i.postimg.cc/nzPnMfdW/Screen-Shot-2019-07-24-at-7-06-42-PM.png)](https://postimg.cc/8JM2n9gd)

**Comment by HDVinnie** [comment]
Closed in UNIT3D v1.9.4 Release
