### ISSUE TITLE
cant see most recent chat line until a new line of text

### ISSUE THREAD

**Issue by catfatwm** [HDInnovations/UNIT3D#479]
### Issue Type
- [x] Bug Report

In chromium fork vivaldi, and also chrome, i cant see the most recent line of text until someone else says something.

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
Unable to replicate this on my Mac using safari, firefox or vivaldi. If others chime in and this is a valid issue I will reopen.
