### ISSUE TITLE
Pages after 1 load at the bottom of page results

### ISSUE THREAD

**Issue by rentalweb** [HDInnovations/UNIT3D#481]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

Don't know the version #, etc. but this relates to xxx using Chrome browser. I haven't tested site in other browsers.

### Expected Behavior:

When viewing a list of torrents and clicking on the next page, I'm used to being taken to the top of the next page of results.

### Actual Behavior:

Whenever browsing a list of torrents, clicking link for the next page takes me to the bottom of the next page and I have to scroll up to the top manually. (Although, if I scroll up slightly before the new page has loaded, site leaves me at the top of the page.)

### Steps To Reproduce The Problem:
(In Chrome) view a list of torrents and click on the link for the next page.

**Comment by HDVinnie** [comment]
This is indeed a Google Chrome only bug. I will try to resolve it.
