### ISSUE TITLE
Bookmarks not deleting correctly

### ISSUE THREAD

**Issue by rentalweb** [HDInnovations/UNIT3D#482]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Expected Behavior:

Clicking one of the Xs on the bookmark page should remove bookmark from the corresponding item. 

I don't know if un-bookmarking is supposed to also download the torrent, but that would be a nice feature if it occurred consistently.

### Actual Behavior:

When viewing a list of bookmarks from the bookmark page, clicking on the X at the end of row sometimes downloads the listed torrent.  Sometimes it downloads the torrent listed on another line. Sometimes it doesn't download anything. In each case, I see a pop up message telling me that the bookmark has been removed, and if I click on the torrent's details page, bookmarked is unchecked. But the torrent is still listed on my bookmark page - even after refreshing. It is gone now that I've logged out and back in.

### Steps To Reproduce The Problem:
1. View bookmark list
2. Click x to delete a bookmark
3.

**Comment by HDVinnie** [comment]
Im not able to replicate this on demo site which is up to date with master branch. If others can please chime in and ill reopen the isssue. For me on two different machines and two different browsers the bookmarks system works fine.
