### ISSUE TITLE
Some Chinese translation problems

### ISSUE THREAD

**Issue by haig233** [HDInnovations/UNIT3D#485]
### Issue Type
- [x] Enhancement
- [x] Technical Discussion

Some Chinese translation problems, please correct the project team.
Or you can provide a file path so we can fix it ourselves

**Comment by singularity43** [comment]
/resources/lang/cn/

Any strings that are reported follow this naming convention:

If you see lang('common.wordhere') / trans('common.wordhere') referenced anywhere, it would be in common.php.
If you see lang('user.wordhere') / trans('user.wordhere') referenced anywhere, it would be in user.php.
If you see lang('auth.wordhere') / trans('auth.wordhere') referenced anywhere, it would be in auth.php.

And so on.

Hope this helps.

**Comment by haig233** [comment]
@singularity43 thank you

**Comment by HDVinnie** [comment]
@haig233 are you going to wind up making a PR or can I close this?

**Comment by haig233** [comment]
@HDVinnie I want to let other Chinese users see it, so that they can modify it.

**Comment by singularity43** [comment]
@haig233 Just gave me a wonderful idea. I am going to work on a Crowdsourcing feature so that staff can assign users rights to modify translation files.  All trackers could use this and it would let each community have their perfect translations.

**Comment by haig233** [comment]
@singularity43 This is a great idea, I will pay attention to the progress of the project in time.

**Comment by pbodq2** [comment]
> @singularity43 This is a great idea, I will pay attention to the progress of the project in time.

I have re-translated the folder lang/cn and lang/tw. Improved all machine translations and cover about 70% English scope. In the coming few weeks. I will go on and add lots of labels. Also I will focus on the TMDB API.


You may refer to my fork as a base version to save your time. I try to make a pull request to the master but sometimes Github may rejets it. You may not see my works on this branch. Therefore, you better direct fork mine.

**Comment by haig233** [comment]
@pbodq2 As of today (June 19, 2019), most of the Chinese translations on the website have been improved, but there are still a small number of tips that are still not translated (see the demo site). I hope you can continue to translate, thank you for your contribution.

**Comment by pbodq2** [comment]
> @pbodq2 As of today (June 19, 2019), most of the Chinese translations on the website have been improved, but there are still a small number of tips that are still not translated (see the demo site). I hope you can continue to translate, thank you for your contribution.

I think those left is not important and not frequently faced, so I spend time on other things. Also, those English sentences inside Controllers are not yet relocated to View. It is not the best phase to translate it.
Some are even inside Javascript and pages refactoring is needed.

If you insist on it, I may start the work 1-2 weeks later

**Comment by haig233** [comment]
> > @ pbodq2截至今天（2019年6月19日），网站上的大多数中文翻译都有所改进，但仍有少量提示仍未翻译（参见演示网站）。我希望你能继续翻译，谢谢你的贡献。
> 
> 我认为那些遗留下来并不重要且不经常面对，所以我花时间在其他事情上。此外，控制器内的那些英语句子尚未重新定位到View。翻译它不是最好的阶段。
> 有些甚至在Javascript中，需要重构页面。
> 
> 如果你坚持下去，我可能会在1-2周后开始工作

I think that is not very friendly to users in mainland China, because users will not consider development issues for you, they focus on the experience. Of course, you are the developer, or you decide.
