### ISSUE TITLE
[REQ] Automatic update procedure, simple and fast!

### ISSUE THREAD

**Issue by Titeuf49** [HDInnovations/UNIT3D#512]
### Issue Type
- [ ] Bug Report
- [x ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: 18.9

### Feature Idea:
Hello,
Is it possible that you make a procedure for the updates, automatic, simple and repide?
thank you in advance,
Warmest regards

**Comment by HDVinnie** [comment]
There already is.

`php artisan git:update`

[VIDEO] Using UNIT3D's GitUpdater Command
https://www.youtube.com/watch?v=tlNUjS1dYMs

**Comment by Titeuf49** [comment]
Hi HDVinnie, look this:
[https://imgur.com/a/JUXC4M6](url)
Thank

**Comment by HDVinnie** [comment]
@Titeuf49 either your provider is blocking it or it was offline. I just tested and its working fine. Try again. If still doesnt work I would check if your provider is blocking git.
