### ISSUE TITLE
New install and the website is not ok.

### ISSUE THREAD

**Issue by evil4u** [HDInnovations/UNIT3D#534]
I did a new install on a new server. And I got this.

I'm using ubuntu 16.04 new install, and I used Automated Installer.

Can you shed some light on what's going on.

<img width="1237" alt="screenshot 2019-01-30 at 16 48 03" src="https://user-images.githubusercontent.com/46950707/52000359-d3583f80-24b4-11e9-902b-17e8bdf5ea4b.png">

**Comment by HDVinnie** [comment]
Did you encounter ANY ERRORS OR WARNINGS during the install process. As it appears your css/js didn't compile.

`npm run prod` would solve it if this is the case.

**Comment by evil4u** [comment]
$ npm run prod

> @ prod /var/www/html
> npm run production


> @ production /var/www/html
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js



 ERROR  Failed to compile with 7 errors                                                                                                                  19:09:04

These relative modules were not found:

* ../../../node_modules/img/pipes/blue.png in ./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--7-4!./node_modules/sass-loader/lib/loader.js??ref--7-5!./resources/sass/themes/dark-blue.scss
* ../../../node_modules/img/pipes/green.png in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/lib/loader.js??ref--8-5!./resources/sass/themes/dark-green.scss
* ../../../node_modules/img/pipes/pink.png in ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/sass/themes/dark-pink.scss
* ../../../node_modules/img/pipes/purple.png in ./node_modules/css-loader??ref--10-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--10-4!./node_modules/sass-loader/lib/loader.js??ref--10-5!./resources/sass/themes/dark-purple.scss
* ../../../node_modules/img/pipes/red.png in ./node_modules/css-loader??ref--11-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--11-4!./node_modules/sass-loader/lib/loader.js??ref--11-5!./resources/sass/themes/dark-red.scss
* ../../../node_modules/img/pipes/teal.png in ./node_modules/css-loader??ref--12-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--12-4!./node_modules/sass-loader/lib/loader.js??ref--12-5!./resources/sass/themes/dark-teal.scss
* ../../../node_modules/img/pipes/yellow.png in ./node_modules/css-loader??ref--13-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--13-4!./node_modules/sass-loader/lib/loader.js??ref--13-5!./resources/sass/themes/dark-yellow.scss
Error: EACCES: permission denied, open '/var/www/html/public/js/twostep.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Function.concatenate.sync (/var/www/html/node_modules/concatenate/lib/concatenate.js:128:8)
    at FileCollection.merge (/var/www/html/node_modules/laravel-mix/src/FileCollection.js:30:36)
    at ConcatenateFilesTask.merge (/var/www/html/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:18:37)
    at ConcatenateFilesTask.run (/var/www/html/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:11:14)
    at CustomTasksPlugin.runTask (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:35:14)
    at Mix.tasks.forEach.task (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:11:44)
    at Array.forEach (<anonymous>)
    at compiler.plugin.stats (/var/www/html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:11:23)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/var/www/html/node_modules/webpack/lib/Compiler.js:234:21)
    at hooks.afterCompile.callAsync.err (/var/www/html/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/var/www/html/node_modules/webpack/lib/Compiler.js:627:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/var/www/html/node_modules/webpack/lib/Compilation.js:1325:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/var/www/html/node_modules/webpack/lib/Compilation.js:1316:32)
    at _promise1.then._result1 (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2019-01-30T18_09_04_732Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2019-01-30T18_09_04_748Z-debug.log

**Comment by evil4u** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/node_modules/.bin:/usr/local/sbin:/usr/local/b$
9 verbose lifecycle @~prod: CWD: /var/www/html
10 silly lifecycle @~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle @~prod: Returned: code: 2  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `npm run production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /var/www/html
16 verbose Linux 4.4.0-141-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error @ prod: `npm run production`
22 error Exit status 2
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]`

**Comment by HDVinnie** [comment]
next time use something like pastebin lol. Now with those errors I am 10000000% sure you had to have encountered a error during the installer. That error would help.

However assuming you DO NOT HAVE it anymore you can try:

```
sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npm run prod
```

then `php artisan clear:all_cache`

**Comment by evil4u** [comment]
LOL yah my bad.

I did what you told me to do sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npm run prod

Here is pastebin https://pastebin.com/KhBLphQH

Log https://pastebin.com/YfStucQ1

php artisan clear:all_cache

Could not open input file: artisan

**Comment by evil4u** [comment]
And I did not se any errors at first, then I did a reinstall then I got the errors at the end of the install.

**Comment by HDVinnie** [comment]
I cannot help you at this point since something went wrong at install level and you don't know what. You need to format your server and start over. Nothing on server but Ubuntu then run installer. If you have a error during install then stop and open a issue in the installer git.

https://github.com/poppabear8883/UNIT3D-INSTALLER

**Comment by HDVinnie** [comment]
Right from the README....

```
Officially Supported OS's
Ubuntu 16.04 LTS
Ubuntu 18.04 LTS
```

**Comment by singularity43** [comment]
Something happened in a previous commit.

Laravel changed a dependency and that package doesn't play nice with current sass.

This is a bug.

**Comment by HDVinnie** [comment]
Strange I did fresh install and worked fine....ill try again on demo site soon and report back.

**Comment by singularity43** [comment]
You can do the install on 16.

Just change the resolve-url-loader dependency to 2.3.1 until sass conflict is resolved.

**Comment by HDVinnie** [comment]
@evil4u this is now fixed. You can feel free to reinstall using installer.

https://github.com/HDInnovations/UNIT3D/commit/fa5ef231dcf0b5da4c6bb59058279109db024d5c

**Comment by evil4u** [comment]
Thanks :)

**Comment by evil4u** [comment]
YES.

It's working.

Thanks for the work :) and for the help guys.

**Comment by HDVinnie** [comment]
your welcome
