### ISSUE TITLE
Poll suggestions

### ISSUE THREAD

**Issue by HVRVKVT** [HDInnovations/UNIT3D#55]
### Poll suggestions:
-  Show result bars in %.
-  Whenever one has voted, make it jump straight to results when revisiting.
-  Announce in chat when user votes on a Poll. The message shouldn't state the username.
-  Make “Allow Commenting” an option when creating a new poll.
-  Show polls on home page, should disappear after user has voted.

**Comment by HDVinnie** [comment]
The Poll System could use a full rewrite (I rushed it when first made it) or maybe just some refactoring. Im going to start working on it this weekend. Ill post updates here.

**Comment by HDVinnie** [comment]
I have made progress on this.......should have the changes up this weekend.

**Comment by Hyleus** [comment]
>Show polls on home page, should disappear after user has voted.
This should only be limited to one poll, otherwise it pollutes the home page to much.
