### ISSUE TITLE
Steam api - games

### ISSUE THREAD

**Issue by rs3mk** [HDInnovations/UNIT3D#563]
### Issue Type
- [ ] Bug Report
- [X] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

Is it possible to add this steam api to extract game information?

https://stackoverflow.com/a/22290599/10272816

Thanks

**Comment by HDVinnie** [comment]
Were already adding a games API so no.

https://github.com/HDInnovations/UNIT3D/issues/475
