### ISSUE TITLE
errors with transmission

### ISSUE THREAD

**Issue by Nap4k** [HDInnovations/UNIT3D#565]
### Issue Type
- [x] Question

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Actual Behavior:

SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'left' at row 1 (SQL: insert into `peers` (`peer_id`, `md5_peer_id`, `info_hash`, `ip`, `port`, `agent`, `uploaded`, `downloaded`, `seeder`, `left`, `torrent_id`, `user_id`, `updated_at`, `created_at`) values (2d5452323932302d6f6578716f65316735693977, 1ddae910442d64b1aebdceff5e2bda3e, da5f3f9c920b660144020104057d130f6c97416e, 95.211.90.134, 7623, Transmission/2.92, 0, 0, 0, 1.844674407371E+19, 637, 1762, 2019-02-07 18:01:37, 2019-02-07 18:01:37)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'left' at row 1 (SQL: insert into `peers` (`peer_id`, `md5_peer_id`, `info_hash`, `ip`, `port`, `agent`, `uploaded`, `downloaded`, `seeder`, `left`, `torrent_id`, `user_id`, `updated_at`, `created_at`) values (2d5452323932302d6f6578716f65316735693977, 1ddae910442d64b1aebdceff5e2bda3e, da5f3f9c920b660144020104057d130f6c97416e, 95.211.90.134, 7623, Transmission/2.92, 0, 0, 0, 1.844674407371E+19, 637, 1762, 2019-02-07 18:01:37, 2019-02-07 18:01:37)) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'left' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'left' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
--

### Steps To Reproduce The Problem:
1. dont know getting error with transmission even blocked as client.
2.
3.

**Comment by singularity43** [comment]
Transmission is reporting really long values.

Just needs some sanitization to fix.

Will look later.

**Comment by HDVinnie** [comment]
1.844674407371E+19 is a ridiculous amount in bytes. Dude is cheating or client is messed up.

**Comment by HDVinnie** [comment]
@Nap4k theres no way ever someone is going to be able to announce `1.844674407371E+19` bytes in a announce interval. Either ban said user (for cheating) or blacklist the client. 

`1.844674407371E+19` Bytes is `16777216` TB
