### ISSUE TITLE
Moderating suggetions

### ISSUE THREAD

**Issue by HVRVKVT** [HDInnovations/UNIT3D#57]
## A few suggestions to make moderating more efficient and a better experience for staffers and members.

- **Add another queue named "Processing" or something similar.**
It will let other staffers know that one is currently processing said upload; Saving time and preventing several staffers from contacting the uploader. To sit between denied/approved.

- **Rejecting uploads.**
Rejecting or placing a torrent in "Processing" will prompt a message box to be filled like when deleting a torrent.
Staff can this way quickly give feedback on what needs to be corrected/reason of rejection. 
Optimally the box should send a PM to the uploader auto filling the Subject with "torrentName" or even better, a clickable link.

- **Hide unapproved torrents from members.**
Currently unapproved torrents show up in the torrent list, front page and in shoutbox. This is inelegant and should only be visible in the staff moderation queue and on the uploaders profile until approved.

- **Uploads and filled requests shouldn’t unlock achievements until it's approved**
Self-explanatory

**Comment by Red227** [comment]
Excellent suggestions!

**Comment by ScroogeHD117** [comment]
Nice one!

**Comment by MrG01** [comment]
re: point 4 - `filled requests` already only unlock achievement when approval. 
Uploads however do not, but this has been corrected, however not implemented yet.
