### ISSUE TITLE
Problem setting the timezone

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#573]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: 1.9

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.15

-- Database Driver & Version: mariadb 10.2.21

-- Web Server Driver & Version: nginx 1.10.3

-- OS Driver and Version: Debian 9.7

### Expected Behavior:
Change timezone

### Actual Behavior:
I can not change timezone through the dashboard. Always return to UTC.
In app.php it is changed but has no effect.

### Steps To Reproduce The Problem:
1. In dashboard choose Config Manager
2. In App change timezone to UTC-3 and go out.
3. Enter setup again and timezone continues as UTC.

**Comment by HDVinnie** [comment]
Clear your config cache and refresh perms.

`sudo chown -R www-data: storage bootstrap public config && php artisan clear:all_cache`

**Comment by tuxfrw** [comment]
Hi,
It worked. Do you think it's interesting to put the command in crontab? php artisan clear: all_cache?

**Comment by HDVinnie** [comment]
not really.....caching them is a performance boost.

`php artisan clear:all_cache`
make your config changes
`php artisan set:all_cache` <--- to recache

We will probably add buttons in config manager so can set and clear cache right from manager.

**Comment by tuxfrw** [comment]
Very good! Thanks for the system!
