### ISSUE TITLE
Fix compatability with Jackett

### ISSUE THREAD

**Issue by KristupasSavickas** [HDInnovations/UNIT3D#574]
Currently, it's required of the user to pass `type` parameter when querying torrents or it defaults to BD50. This causes Jackett to return limited results, as only one type is used for filtering. This should be fixed so that queries with no type match against all types.

See: https://github.com/Jackett/Jackett/issues/1524, https://github.com/Jackett/Jackett/pull/1489#issue-126680453.

**Comment by HDVinnie** [comment]
Not sure I follow. Users are NOT required to pass TYPE filter.

https://unit3d.org/filterTorrents?_token=2BWEu3yhdT7z8LaCm8dKf4ORLQNl8I2YaeMIcwp2&search=&description=&uploader=&imdb=&tvdb=&view=list&tmdb=&mal=&types=&page=0&qty=25

With no types selected all results are returned.

With 1080p TYPE selected only 1080p is returned

https://unit3d.org/filterTorrents?_token=2BWEu3yhdT7z8LaCm8dKf4ORLQNl8I2YaeMIcwp2&search=&description=&uploader=&imdb=&tvdb=&view=list&tmdb=&mal=&types%5B%5D=1080p&sorting=created_at&direction=desc&page=0&qty=25
