### ISSUE TITLE
Suggestion: Encrypted IPs in the database

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#575]
### Issue Type
- [ ] Bug Report
- [x] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: 1.9

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.15

-- Database Driver & Version: Mariadb 10.2.21

-- Web Server Driver & Version: Nginx 1.10.3

-- OS Driver and Version: Debian 9.7

### Expected Behavior:
The system could have a way to encrypt users' IPs in the database to improve the anonymity of user data. Would it be possible?

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
DONE

**Comment by tuxfrw** [comment]
thanks!!!!!!  :D

**Comment by tuxfrw** [comment]
An error 500 has occurred after the change in Activity Log:

The payload is invalid. (View: /var/www/html/resources/views/Staff/activity/index.blade.php) {"userId":4,"email":"xxxxx@xxxx.com","exception":"[object] (ErrorException(code: 0): The payload is invalid. (View: /var/www/html/resources/views/Staff/activity/index.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:191, Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:191)

**Comment by HDVinnie** [comment]
Did you even read the commit notes?
https://github.com/HDInnovations/UNIT3D/commit/c121c9ac84e0271a5c3dbba3746773b7c7870b3a

```
you will have to truncate two tables to remove unencrypted records after pulling in this update.
- TRUNCATE log_activities;
- TRUNCATE clients;
- PLEASE NOTE YOUR APP_KEY IN YOUR .ENV IS USED FOR ENCRYPTION.  All encrypted values are encrypted using OpenSSL and the AES-256-CBC cipher. DO NOT LOOSE OR SHARE YOUR KEY!!!
```

**Comment by tuxfrw** [comment]
Ummm I understood. I will do this. Thank you!
