### ISSUE TITLE
Add option to upload other files.

### ISSUE THREAD

**Issue by xonexx** [HDInnovations/UNIT3D#580]
1. Current Upload From Doesn't compatible with Other File upload. Because it Doesn't Have Option To Manually add poster or Image on Torrents. Also it says IMDB & TMDB id is required. But Other Files Doesn't Have IMDB or TMDB ID. Even some movie & TV shows doesn't have IMDB ID. 

2. Current UI is not mobile friendly. But in Today 70% internet users uses mobile to browse internet. Please Adopt some mobile friendly theme design.  

###UNIT3D is already a Good Application , but adding extra features will make it more flexible to others.

**Comment by HDVinnie** [comment]
1) UNIT3D is aimed for Movies and TV use as stated in README and repo sub-title.
2) If IMDB or TMDB is not available then leave it the default 0 and it wont fail....
3) SASS is being worked on.
4) Use issue template. One topic per issue.
5) UNIT3D is open source. So feel free to contribute.
