### ISSUE TITLE
use POEdit Tool to edite languages

### ISSUE THREAD

**Issue by croplex** [HDInnovations/UNIT3D#608]
### Issue Type
- [ ] Bug Report
- [X ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
POEdit doesnt even support PHP files. Not something we are going to use.
