### ISSUE TITLE
Error when deleting private message in chat

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#609]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.9.0

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.9

-- Database Driver & Version: MySQL 5.7.23

-- Web Server Driver & Version: nginx/1.15.0

-- OS Driver and Version: Ubuntu 18.04.1

When attempting to delete a private message in chatbox a refresh is required to remove the message. I replicated this issue on the demo site. In laravel log shows the following error:
```
Argument 1 passed to App\Events\MessageDeleted::__construct() must be an instance of App\Models\Message, null given, called in /var/www/html/app/Repositories/ChatRepository.php on line 227 {"userId":3,"email":"none@none.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Events\\MessageDeleted::__construct() must be an instance of App\\Models\\Message, null given, called in /var/www/html/app/Repositories/ChatRepository.php on line 227 at /var/www/html/app/Events/MessageDeleted.php:40)
```

### Steps To Reproduce The Problem:
1. Send a pm to another user from within the chatbox.
2. In the newly created tab, attempt to delete the message
3. Refresh page to remove message then check laravel log

**Comment by HDVinnie** [comment]
Thanks for report.
