### ISSUE TITLE
Beep for Purovicio Chat

### ISSUE THREAD

**Issue by Alk3r0** [HDInnovations/UNIT3D#615]
[feature Idea] I Always left the page open of Purovicio. And I always send a greeting or question on the Chat area but if there is No one then I'm doing searches on the Web and when I return I notice that someone left me a message. My question is it will be possible to put a Beep in the Chat room which indicates that they responded. I have seen that it can be activated and deactivated and that way the user choose. Thank You in advance and keep up with the good work [Feature Idea]

**Comment by HDVinnie** [comment]
No idea what Purovicio is or what your getting at.....there already optional chat audibles.

**Comment by HDVinnie** [comment]
Hi @Alk3r0 ,

You've created an issue, but haven't provided clear details on what you want. To prevent issue tracker clutter, this issue will now be closed. Please provide the information needed below and I will re-open this issue if needed.

In the future use our Issue Template. Its there and preloaded for a reason.
