### ISSUE TITLE
Staff tools torrent feature

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#616]
### Issue Type
- [x] Question

### End User Info
-- UNIT3D Version: 1.9

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.15

-- Database Driver & Version: Mariadb 10.2.22

-- Web Server Driver & Version: Nginx 1.10.3

-- OS Driver and Version: Debian 9

### Expected Behavior:
Torrent should be no longer featured after the cut-off date or not?

### Actual Behavior:
Torrent has gone from featured (date limit) and continues to be shown. I have not found a way to remove the featured torrent.
https://i.imgur.com/Pw80QuL.png

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
@tuxfrw When did you feature said torrent? You can check in DB in `featured_torrents` table.

**Comment by HDVinnie** [comment]
Also a bit more information needed since Im not able to replicate this and havent ever seen anyone have this issue.

1) If you SSH to your server and run `date` what does it return?
2) In `config/app.php` what is `timezone` set to? Does it match server?
3) (Most Likely Your Mistake) Are you sure you set the crontab?

**Comment by tuxfrw** [comment]
> Also a bit more information needed since Im not able to replicate this and havent ever seen anyone have this issue.
> 
> 1. If you SSH to your server and run `date` what does it return?
# date
seg mar  4 20:16:56 -03 2019
> 2. In `config/app.php` what is `timezone` set to? Does it match server?
 'timezone' => 'America/Sao_Paulo',
> 3. (Most Likely Your Mistake) Are you sure you set the crontab?
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1

**Comment by tuxfrw** [comment]
> Also a bit more information needed since Im not able to replicate this and havent ever seen anyone have this issue.
> 
> 1. If you SSH to your server and run `date` what does it return?
seg mar  4 20:24:21 -03 2019
> 2. In `config/app.php` what is `timezone` set to? Does it match server?
'timezone' => 'America/Sao_Paulo',
> 3. (Most Likely Your Mistake) Are you sure you set the crontab?
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1

**Comment by HDVinnie** [comment]
Running `date` should return something like `Mon Mar  4 22:18:30 UTC 2019` with the TIMEZONE. 

Not sure what -03 is but this appears to be a time issue.

**Comment by HDVinnie** [comment]
Also for the more obvious. Check your logs for any errors related.

**Comment by tuxfrw** [comment]
-03 is the time zone of the server which is GMT -03:00. I do not know if I could explain to you what's going on. I'll send another image.
https://i.imgur.com/AfyUorK.png

**Comment by HDVinnie** [comment]
Yeah I see that. Im just not able to replicate it. I really need to see the `created_at` value for that featured torrent. You can check in DB in featured_torrents table.

Also try running `php artisan auto:remove_featured_torrent` to double check its not a cron issue.

**Comment by tuxfrw** [comment]
Running php artisan auto:remove_featured_torrent works!

featured_torrents table before "php artisan auto:remove_featured_torrent":

|1|5|1|2019-02-22 21:59:12|2019-02-22 21:59:12
|2|4|8|2019-02-23 01:07:35|2019-02-23 01:07:35
|3|4|9|2019-02-23 01:13:29|2019-02-23 01:13:29
|4|4|16|2019-02-23 18:05:32|2019-02-23 18:05:32
|5|4|26|2019-02-26 09:52:01|2019-02-26 09:52:01
|6|4|30|2019-03-04 10:52:10|2019-03-04 10:52:10
|7|4|31|2019-03-04 11:08:59|2019-03-04 11:08:59
|8|4|19|2019-03-04 18:07:06|2019-03-04 18:07:06

featured_torrents table after "php artisan auto:remove_featured_torrent":

|6|4|30|2019-03-04 10:52:10|2019-03-04 10:52:10
|7|4|31|2019-03-04 11:08:59|2019-03-04 11:08:59
|8|4|19|2019-03-04 18:07:06|2019-03-04 18:07:06

**Comment by HDVinnie** [comment]
Then as I expected your crontab is not working or set properly.

```
* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1 to crontab. /path/to/artisan becomes whatever directory you put the codebase on your server. Example * * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1
```

You will have to see why cron is not running on your server. If you don't fix it none of these scheduled commands will run which means you not getting BON, Warnings, Etc.

https://github.com/HDInnovations/UNIT3D/blob/master/app/Console/Kernel.php

**Comment by tuxfrw** [comment]
But before, I ran in the shell the same command that is in crontab, and even then it did not work.
This I found strange because even manually running "php /var/www/html/artisan schedule:run >> /dev/null 2>&1" did not work.
The answer he returned was something of the sort: that there was no schedule.

**Comment by HDVinnie** [comment]
All `php artisan auto:remove_featured_torrent` does is manually run the cron. Since that is working it means something is wrong with your cron scheduler and not UNIT3D.

**Comment by tuxfrw** [comment]
I discovered where the error is in /etc/crontab. When I copied from your manual I did not realize it, but you did not include "root" in the pro /etc/crontab statement.
For sure the /etc/crontab was in error.  :)

* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1 to crontab. /path/to/artisan becomes whatever directory you put the codebase on your server. Example * * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1

Can be change to:

* * * * * root php /path/to/artisan schedule:run >> /dev/null 2>&1 to crontab. /path/to/artisan becomes whatever directory you put the codebase on your server. Example * * * * * root php /var/www/html/artisan schedule:run >> /dev/null 2>&1

**Comment by HDVinnie** [comment]
`root` is not needed. Maybe for Debian but not Ubuntu.

**Comment by tuxfrw** [comment]
Not really. If you use /etc/crontab you need to specify which user will run the command. It has always been like this on any *NIX... Debian, Ubuntu, RedHat, BSDs like: FreeBSD, OpenBSD, NetBSD and others.  When you use "crontab -e" you are not using /etc/crontab but rather a crontab specific to the user you are logged in. crontabs are located in: /var/spool/cron/crontabs/ and not in /etc/crontab. Just look at the man. Try for example doing a crontab -e -u www-data :)
Look in: man 5 crontab
