### ISSUE TITLE
Problem with country Brazil and language

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#640]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: 1.9.1

-- Laravel Version: 5.8.3

-- PHP Version: 7.2.16

-- Database Driver & Version: Mariadb 10.2.22

-- Web Server Driver & Version: nginx 1.10.3

-- OS Driver and Version: Debian 9

### Actual Behavior:
When selecting country Brazil the language that appears in the torrents is not pt_BR.

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by tuxfrw** [comment]
![torrent](https://user-images.githubusercontent.com/20425009/54223441-44d4d600-44d6-11e9-80a2-26a70b3a464a.png)

**Comment by HDVinnie** [comment]
Is there a big difference between pt and pt_br?

I see the issue here the short code is wrong. br is not correct. Ill push a fix.

**Comment by tuxfrw** [comment]
Hi Vinnie,
There was an error with the flag of Brazil that no longer appears. But the language fixed.
![bandeira](https://user-images.githubusercontent.com/20425009/54227123-03482900-44de-11e9-9ec2-a995ba65493c.png)

**Comment by HDVinnie** [comment]
@tuxfrw fixed
