### ISSUE TITLE
Error 500 after last update

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#643]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: 1.9.1

-- Laravel Version: 5.8.3

-- PHP Version: 7.2.16

-- Database Driver & Version: Mariadb 10.2.22

-- Web Server Driver & Version: nginx 1.10.3

-- OS Driver and Version: Debian 9

### Actual Behavior:
Error 500
![erro_500](https://user-images.githubusercontent.com/20425009/54306074-55a14c80-45a7-11e9-945e-59c500d3427e.PNG)

### Steps To Reproduce The Problem:
1. Click any torrent
2.
3.

**Comment by Havenstd06** [comment]
You have probably miss something, i've update manually and it working fine

**Comment by tuxfrw** [comment]
> You have probably miss something, i've update manually and it working fine

I only use "php artisan git: update", no other and only noticed after this last update.

**Comment by aronpc** [comment]
In routes : Category ID is required,not optional.
https://github.com/HDInnovations/UNIT3D/blob/8bb397c29c6516a1aa330868dc5c0d47ff0721c4/routes/web.php#L234

But in the torrent.blade it's not passed

https://github.com/HDInnovations/UNIT3D/blob/8bb397c29c6516a1aa330868dc5c0d47ff0721c4/resources/views/torrent/torrent.blade.php#L636

https://github.com/HDInnovations/UNIT3D/blob/8bb397c29c6516a1aa330868dc5c0d47ff0721c4/resources/views/torrent/torrent.blade.php#L638

https://github.com/HDInnovations/UNIT3D/blob/8bb397c29c6516a1aa330868dc5c0d47ff0721c4/resources/views/torrent/torrent.blade.php#L645

https://github.com/HDInnovations/UNIT3D/blob/8bb397c29c6516a1aa330868dc5c0d47ff0721c4/resources/views/torrent/torrent.blade.php#L647

**Comment by HDVinnie** [comment]
Its a valid bug.....ill push fix in a few.

**Comment by Havenstd06** [comment]
my bad 😕
