### ISSUE TITLE
Torrent  search filter

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D#644]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.9.1

-- Laravel Version: 5.8.3

-- PHP Version: php7.3.2-3+ubuntu18.04.1+deb.sury.org+1

-- Database Driver & Version: 5.7.25-0ubuntu0.18.04.2

-- Web Server Driver & Version: nginx

-- OS Driver and Version: Ubuntu

### Steps To Reproduce The Problem:
1. Torrent List,Catalogs,groups and Cards
2. No spinning wheel by filter torrent page 1 and 2 usw
3. please fix

### Possible Fix:
https://abload.de/img/searchpqj3r.png

**Comment by HDVinnie** [comment]
Please pay attention before opening a invalid issue. This was already fixed.

https://github.com/HDInnovations/UNIT3D/commit/e80c797ffcda4eb30f1938a4a66f2efd29fc011d

**Comment by masterfo78** [comment]
Did it see and edited doesn't work

**Comment by HDVinnie** [comment]
Works fine for me on 4 browsers. You probably noobed it and didn't rebuild your assets with `nom run prod`
