### ISSUE TITLE
Redirect new people to the Rules page

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D#646]
Hi,

it would be nice if new people would be forced onto the rules page and to tick a box at the bottom to agree that they've read and understood those. Obviously not all of them will actually read them, but it should encourage people to read them and make them aware that there are in fact rules.

**Comment by HDVinnie** [comment]
Ok so I thought this over and there is two ways we could handle this:
Regardless we add a new `read_rules` column to users table.

1) We add a `CheckIfReadRules.php` middleware. This middleware checks if the `read_rules` column is true or false for said user. If false they are redirect to rules page where they will have to accept them.
`Pros:` They cant browse site until they accept.
`Cons:` This middleware check is run on `ever` request.

2) We add the check instead to the `LoginController.php`. The logic would check if the `read_rules` column is true or false for said user. If false they are redirect to rules page where they will have to accept them.
`Pros:` Were not running the check on ever request.
`Cons:` Once user is redirected they could just leave page without accepting. However upon there next and ever login forward they will be redirected to rules page until they accept.

**Comment by HDVinnie** [comment]
@xR4E which works better for what your wanting?

**Comment by xR4E** [comment]
"This middleware check is run on ever request." 

What does it mean in practical terms? Is it something one notices or just a performance thing?

**Comment by HDVinnie** [comment]
It just means that on every single request a user makes to the site then that check will be ran about rules. Like any page they visit, leaving comment, thanks, etc. So yes its more just a performance thing.

**Comment by LayerCorp** [comment]
How was this implemented? Maybe requesting the middleware on every request for every user can have a bad performance results in some enviroments.

**Comment by HDVinnie** [comment]
@LayerCorp no middelware was used.

https://github.com/HDInnovations/UNIT3D/commit/89ba76ebac74f0d8fcab5b8238ab257bec4924a1
