### ISSUE TITLE
IRC Announce

### ISSUE THREAD

**Issue by Sc4nd4l** [HDInnovations/UNIT3D#651]
### Issue Type
- [X] Bug Report

### End User Info
-- UNIT3D Version: 1.9.1

-- Laravel Version: 5.8.3

-- PHP Version: 7.3.3

### Expected Behavior:
Torrent uploads -> Announce to IRC channel

### Actual Behavior:
Torrent uploads, but gets redirected to upload form. Bot then joins the channel and exists instantly. It then display a 500 error, but torrent is uploaded. 

### Steps To Reproduce The Problem:
1. Upload torrent, add IRC announce config for bot 
2. Watch in irc server as the bot connects and disconnects.

**Comment by HDVinnie** [comment]
Provide the error 500 from logs.

**Comment by Sc4nd4l** [comment]
`2019/03/23 12:11:35 [error] 21723#21723: *197059 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 84.x.4x.xx., server: channelx.online, request: "POST /upload HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/channelx.online.sock", host: "channelx.online"
2019/03/23 12:22:29 [error] 21722#21722: *197369 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 84.xx.4x.xx, server: channelx.online, request: "POST /upload HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/channelx.online.sock", host: "channelx.online"
2019/03/23 12:33:25 [error] 21721#21721: *197783 open() "/var/www/html/public/img/rlm.png" failed (2: No such file or directory), client: x.16x.1.x0, server: channelx.online, request: "GET /img/rlm.png HTTP/1.1", host: "channelx.online"`

**Comment by HDVinnie** [comment]
No. You said error 500. I care less about NGINX log. You need to post the error from `/var/www/html/storage/logs` that has to do with your issue.

**Comment by Sc4nd4l** [comment]
`[2019-03-23 09:26:57] prod.ERROR: Unable to rewrite key "channels.0" in config, rewrite failed {"userId":5,"exception":"[object] (Exception(code: 0): Unable to rewrite key \"channels.0\" in config, rewrite failed at /var/www/html/vendor/infinety-es/config/src/Rewrite.php:53)
[stacktrace]
#0 /var/www/html/vendor/infinety-es/config/src/Rewrite.php(28): Infinety\\Config\\Rewrite->toContent('<?php\
/**\
 * NO...', Array, true)`

Seems to be a misconfig by me in the irc-bot.conf.

**Comment by HDVinnie** [comment]
Delete your logs. Update the `irc-bot`config manually. Then try bot again.

**Comment by Sc4nd4l** [comment]
Same issue, no logoutput and a 504 error now. 

`
    'enabled'      => 'true',
    'hostname'     => 'thisismyhostname',
    'server'       => '167.99.220.217',
    'port'         => '6667',
    'username'     => 'AnnounceBot',
    'password'     => 'Announcetest132',
    'channels'     => ['#announce'],
    'nickservpass' => 'false',
    'joinchannels' => 'true',
];`
