### ISSUE TITLE
Login question，my URL became http://page/rules.1.

### ISSUE THREAD

**Issue by buaapyj** [HDInnovations/UNIT3D#655]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [x] Question

### End User Info
-- UNIT3D Version: Currently Running UNIT3D Nex-Gen Torrent Tracker v1.9.2

-- Laravel Version: Laravel Framework 5.8.7

-- PHP Version: 

-- Database Driver & Version: mysql 5.7

-- Web Server Driver & Version: nginx，nginx version: nginx/1.15.8

-- OS Driver and Version: ubuntu 16.04

### Expected Behavior:
after login in ,It shoude be redict to http://my-domain/rules.1.

### Actual Behavior:

It redict to http://page/rules.1.
I have no idea about why it becomes page ?

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
It works fine. Either your other.php config is wrong or you manually installed and didn't set your APP_URL in your .env.

https://github.com/HDInnovations/UNIT3D/commit/4ac54b9714f6d002181b6c6d5dbf9dc581e7f277
