### ISSUE TITLE
anonymous comments on news.

### ISSUE THREAD

**Issue by Franciscomfrank** [HDInnovations/UNIT3D#656]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: v1.9.2

-- Laravel Version:  5.8.7

-- PHP Version php7.3.3-1+ubuntu18.04.1+deb.sury.org+1:

-- Database Driver & Version: 5.7.25-0ubuntu0.18.04.2

Dear HDVinnie, I do not know if it is a bug or is the way to work. When making a comment anonymously in a news item, the name of the person doing it appears in the chat. "Should I be anonymous?" the same thing does not happen in the comments of the torrents. the same does not happen in requests of torrents, nor in the comments of these.
![unknown](https://user-images.githubusercontent.com/49216960/55446157-dc3cbe80-5594-11e9-8f77-0ef1322ac23e.png)

**Comment by masterfo78** [comment]
This picture and comment by torrents not article

**Comment by Franciscomfrank** [comment]
> article

![noticias2](https://user-images.githubusercontent.com/49216960/55521772-8893a900-5658-11e9-94bb-62439a988c41.png)


if it corresponds to the estimated news.
The problem was resolved.

Attached capture.
