### ISSUE TITLE
Indicate when chat tab contains new messages since it was last active

### ISSUE THREAD

**Issue by shlandturtle** [HDInnovations/UNIT3D#659]
### Issue Type
- [ ] Bug Report
- [x] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: v1.9.2

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Idea:
Now that the chat has tabs with separate rooms, would be nice if the tab would clearly indicate if there's new messages since the tab was last open for the given user. For example the speech bubble could vary in color or size, as a loop (like constantly change between big and small for example) or the tab could have a small "New" tag on it.
These would clear when the tab is activated. Now with multiple rooms are open, you need to click through all of them to see if anything has been posted.

**Comment by HDVinnie** [comment]
It already functions like that.....red chat bubble by default and green chat bubble when new message comes in and your not on tab. Just tested it myself on demo site.

**Comment by shlandturtle** [comment]
In that case there is a bug since the color hasn't ever changed for me. Tried on light theme too but I don't think it's due to that. On dark theme the chat bubble stays green, on light theme it stays red.
