### ISSUE TITLE
Edit or delete surveys

### ISSUE THREAD

**Issue by Franciscomfrank** [HDInnovations/UNIT3D#661]
Bug Report

End User Info

-- UNIT3D Version: v1.9.2

-- Laravel Version: 5.8.7

-- PHP Version php7.3.3-1+ubuntu18.04.1+deb.sury.org+1:

-- Database Driver & Version: 5.7.25-0ubuntu0.18.04.2

it does not allow editing or deleting a survey already created.
![poll](https://user-images.githubusercontent.com/49216960/55520328-32bc0280-5652-11e9-87ab-6601d5539d95.png)

**Comment by HDVinnie** [comment]
Read and check before opening a new issue. This is a duplicate.

https://github.com/HDInnovations/UNIT3D/issues/380
