### ISSUE TITLE
Mail problem，I can't recieve register mail.

### ISSUE THREAD

**Issue by buaapyj** [HDInnovations/UNIT3D#662]
Issue Type
 Question
End User Info
-- UNIT3D Version: Currently Running UNIT3D Nex-Gen Torrent Tracker v1.9.2

-- Laravel Version: Laravel Framework 5.8.7

-- PHP Version:

-- Database Driver & Version: mysql 5.7

-- Web Server Driver & Version: nginx，nginx version: nginx/1.15.8

-- OS Driver and Version: ubuntu 16.04

Expected Behavior:
after register, I should receive the validation email.

Actual Behavior:
Can't receive mail.
But if I use Reset Password methd, The mail can be received.
The FORGOT YOUR USERNAME method can not receive mail too.

Steps To Reproduce The Problem:
Here is my .env setting.

****************************************
MAIL_DRIVER=smtp
MAIL_HOST=smtp.126.com
MAIL_PORT=465
MAIL_USERNAME=someone@126.com
MAIL_PASSWORD=*********
MAIL_ENCRYPTION=SSL
MAIL_FROM_NAME=ADMIN
MAIL_FROM_ADDRESS=someone@126.com
****************************************

 the result of execution：php artisan test:email
dog@bd095:/var/www/html/UNIT3D$ php artisan test:email
Sending Test Email To ["unit3d@none.com"]
****************************************
*     Email Was Successfully Sent!     *
****************************************

Here is the log viewer:
`
Expected response code 250 but got code "554", with message "554 DT:SPM 126 smtp3,DcmowACXIQg4yaVc7OnKDQ--.44833S2 1554368824,please see http://mail.163.com/help/help_spam_16.htm?ip=124.207.188.68&hostid=smtp3&time=1554368824`

first，I think it's the mail service provider problem，but i use gmail，Yandex mail，the prolem still occurs.

I have two problems:
1, why I can get reset password mail  but register mail error.
2, I can't find the link to  the log viewer page So I must input the url to this page(I see this page url form your answers in issues ).
So any related complete list can I find to view useful manage pages which don't have a link in staff page.

**Comment by HDVinnie** [comment]
This is not a bug. Certain emails like the activation email are processed via a queued job.

Checked `sudo supervisorctl`. If any are failed. Then run `sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload` Then check to make sure there running again. `sudo supervisorctl`

Which should return something like:
```
unit3d-chat-server:unit3d-chat-server_00   RUNNING   pid 19476, uptime 0:07:01
unit3d-queue:unit3d-queue_00               RUNNING   pid 19478, uptime 0:07:01
unit3d-queue:unit3d-queue_01               RUNNING   pid 19477, uptime 0:07:01
```

If continues to fail you need to look at the supervisor logs. 

PS: In future one topic per issue. Your log viewer is in staff dashboard labeled as Laravel Log.

**Comment by buaapyj** [comment]
var/www/html/UNIT3D$ sudo supervisorctl
unit3d-queue:unit3d-queue_00           RUNNING   pid 183376, uptime 3:36:12
unit3d-queue:unit3d-queue_01           RUNNING   pid 183375, uptime 3:36:12
unit3d-socket-io:unit3d-socket-io_00   RUNNING   pid 183374, uptime 3:36:12

Result after  run  sudo supervisorctl

**Comment by buaapyj** [comment]
Also find some useful log from supervisor

[2019-04-04 09:07:02][PWq3yMm69uNMIsxUkvfH9kauF7l9DBLw] Processing: App\Jobs\SendActivationMail
[2019-04-04 09:07:03][PWq3yMm69uNMIsxUkvfH9kauF7l9DBLw] Processing: App\Jobs\SendActivationMail
[2019-04-04 09:07:04][PWq3yMm69uNMIsxUkvfH9kauF7l9DBLw] Processing: App\Jobs\SendActivationMail
[2019-04-04 09:07:04][PWq3yMm69uNMIsxUkvfH9kauF7l9DBLw] Failed:     App\Jobs\SendActivationMail

**Comment by buaapyj** [comment]
thanks for your answer. @HDVinnie but I actually got the error. everytime  I apply register,meanwhile, The Reset Password method executes successfully

Expected response code 250 but got code "554", with message "554 DT:SPM 126 smtp3,DcmowACXIQg4yaVc7OnKDQ--.44833S2 1554368824,please see http://mail.163.com/help/help_spam_16.htm?ip=124.207.188.68&hostid=smtp3&time=1554368824
 

554 DT:SPM code seems like the mail recognized as spam

**Comment by HDVinnie** [comment]
If you restarted supervisor and issue still exists then idk. The error is kinda bland and lacks good info to help debug. I have tested on three site using `sendgrid` and emails send fine weather direct like invite email or a processed job one like activation email.

**Comment by buaapyj** [comment]
@HDVinnie ，I am very grateful for your sincere help. Is it convenient to provide several available mail provider and a sample .env file.
