### ISSUE TITLE
SSL is not supported? My SSL certificate has no sslCertChain!

### ISSUE THREAD

**Issue by laulzgoay** [HDInnovations/UNIT3D#668]
![SA}K}%MO_RIRY O0(H(@96Q](https://user-images.githubusercontent.com/33656556/55664239-d3cad900-585d-11e9-833b-aaf1db79fb31.png)
LOOK！！！
此网站无法提供安全连接 www.sts.tw 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

I'm using cloudflare and using his certificate.My SSL certificate has no sslCertChain!!!

**Comment by silez** [comment]
come on at discord, ill help you

**Comment by laulzgoay** [comment]
Help ME！！！！！！！

**Comment by silez** [comment]
ya, come on at discord at https://discord.gg/vDrhbq
