### ISSUE TITLE
Undefined index: length {"userId":3,"exception":"[object] (ErrorException(code: 0): Undefined index: length at /var/www/html/app/Helpers/Bencode.php:221)

### ISSUE THREAD

**Issue by f1she3** [HDInnovations/UNIT3D#671]
### Issue Type
- [ ] Bug Report

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: 5.8.7 (prod env)

-- PHP Version: 7.3.3 ( 7.3.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) )

-- Database Driver & Version: MySQL 5.7.25

-- Web Server Driver & Version: Nginx 1.15.8

-- OS Driver and Version: Ubuntu 16.04

### Expected Behavior:
Laraval error log should be empty

### Actual Behavior:
I get the error :
 "Undefined index: length {"userId":3,"exception":"[object] (ErrorException(code: 0): Undefined index: length at /var/www/html/app/Helpers/Bencode.php:221)"

I'm not sure when it poped up, maybe it's related to the avatar upload form /unit3d.3/edit
### Steps To Reproduce The Problem:
NOT SURE : go to /unit3d.3/edit, upload an image, only set the title, leave other parameters empty

### Possible Fix:
No idea

### Nginx's error.log:
2019/04/08 12:26:30 [error] 7348#7348: *3072 open() "/var/www/html/public/upload/css/adminlte.css" failed (2: No such file or directory), client: X.X.X.X, server: unit3d.site, request: "GET //upload/css/adminlte.css HTTP/1.1", host
: "Y.Y.Y.Y:443"
2019/04/08 12:41:10 [error] 7350#7350: *3088 open() "/var/www/html/public/upload/css/login.main.css" failed (2: No such file or directory), client: Z.Z.Z.Z, server: unit3d.site, request: "GET //upload/css/login.main.css HTTP/1.1", ho
st: "Y.Y.Y.Y:443"
2019/04/08 13:05:14 [error] 7348#7348: *3111 open() "/var/www/html/public/upload/img/avatar-sign.png" failed (2: No such file or directory), client: X.X.X.X, server: unit3d.site, request: "GET //upload/img/avatar-sign.png HTTP/1.1",
 host: "Y.Y.Y.Y:443"
2019/04/08 15:10:34 [error] 7346#7346: *3241 open() "/var/www/html/public/img/rlm.png" failed (2: No such file or directory), client: A.A.A.A, server: unit3d.site, request: "GET /img/rlm.png HTTP/1.1", host: "unit3d.site"

### Additional info:
I installed UNIT3D using "poppabear8883/UNIT3D-INSTALLER", no error reported during the install, no php-fpm errors, no error from supervisorctl's processes

**Comment by HDVinnie** [comment]
Normal when someone tries to upload a corrupt torrent file.

**Comment by f1she3** [comment]
Ok, so it's the normal behaviour to log such an error ? Other input errors are displayed in the UI

**Comment by HDVinnie** [comment]
Correct by ill adjust the error handling for that down road.
