### ISSUE TITLE
Staff Dashboard button for clear and set cache

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D#672]
### Issue Type
- [x] Enhancement

Adding buttons for owner/admin into the staff dashboard so is possible to clear and set the cache from GUI.
This is a idea from HDVinnie himself in closed issue comment, so here Im asking for this enhancement officialy :)

**Comment by HDVinnie** [comment]
Something you think only Owners should be able to do or admin as well....mods is out of question.

**Comment by LayerCorp** [comment]
Yeah, only owner I think.

**Comment by HDVinnie** [comment]
[![Screen-Shot-2019-04-15-at-6-30-14-PM.png](https://i.postimg.cc/G2G8rfwr/Screen-Shot-2019-04-15-at-6-30-14-PM.png)](https://postimg.cc/FdFsVDHn)

Will be pushed tonight sometime
