### ISSUE TITLE
issues after update

### ISSUE THREAD

**Issue by Nap4k** [HDInnovations/UNIT3D#674]
### Issue Type
- [x] Technical Discussion

### End User Info
-- UNIT3D Version: V.1.9

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Actual Behavior:
https://paste.laravel.io/86937154-307f-4619-a185-5155716190d0
log :: https://paste.laravel.io/e388591c-7338-498b-bef6-fdfbfe002783

### Steps To Reproduce The Problem:
1.just updated login page was not working so try to update with default files auth folder in views
2.
3.

**Comment by HDVinnie** [comment]
`sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npm run prod`

**Comment by Nap4k** [comment]
https://paste.laravel.io/c9261bda-0dfa-4757-b55d-ce937a2bb4ac

still :(

**Comment by HDVinnie** [comment]
your using way to old of a file.....toastr is not part of unit3d.....use the latest auth views.
