### ISSUE TITLE
Chat Text status

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D#678]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [x ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: #.#.#

-- PHP Version: 7.3

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version: ubuntu

### Steps To Reproduce The Problem:
1. Updated their status to in the chat
2.
3.Where to change the text

**Comment by masterfo78** [comment]
why closed

**Comment by HDVinnie** [comment]
Because its extremely bland and not clear as to what your issue is. It maybe sounds like your looking for `User Chat Statuses`. If so there right in staff dashboard.
