### ISSUE TITLE
Client Blacklist

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D#680]
### Issue Type
- [x] Bug Report
- [x] Technical Discussion

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: #.#.#

-- PHP Version:7.3

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.How to lock clients??
2.I tried uTorrent/2.0.4 Build 21586 for the test to lock
3.How do I put this on the blacklist

### Possible Fix:
https://abload.de/img/client7kkfb.png

**Comment by LayerCorp** [comment]
Open client-blacklist.php on your server and ADD that uTorrent manually.

**Comment by masterfo78** [comment]
--------------------------------------------------------------------------
    | Blacklist Clients
    |--------------------------------------------------------------------------
    | An array of clients to be blacklisted which will reject them from announcing
    | to the sites tracker.
    |
    |
    */
    'clients' => [
        'Transmission/2.93', 'Transmission/2.04', 'uTorrent/2040(21586)',
    ],

I added it manually but it does not work anyway

**Comment by masterfo78** [comment]
Can someone help me?

**Comment by masterfo78** [comment]
I have tried it with other clients who are not locked

**Comment by masterfo78** [comment]
ok but if you are on false then the clients are still locked

**Comment by HDVinnie** [comment]
Not from my tests. Maybe you didn't clear cache after altering config?

**Comment by masterfo78** [comment]
ok it's only with 1 and 0 not true or false i got it on false thanks
