### ISSUE TITLE
Remove ajax for entire users table read on some areas

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D#683]
### Issue Type
- [x] Enhancement

### End User Info
-- UNIT3D Version: 1.9.2

Having thousands of users its really a browser (and maybe server) killing job open the "New Message" window on private messages and also the User Gifting option in Staff Dashboard. Everytime anyone open those on my site, browser goes to hell.

Regards!

**Comment by HDVinnie** [comment]
No need to remove it....just need to add caching.

**Comment by LayerCorp** [comment]
Better then! thanks.
