### ISSUE TITLE
500 error as soon add tmdb id

### ISSUE THREAD

**Issue by Nap4k** [HDInnovations/UNIT3D#684]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [x] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: v.1.9.2

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Expected Behavior:
show tmdb data

### Actual Behavior:
Undefined index: first_air_date (View: /var/www/html/resources/views/torrent/torrent.blade.php) {"userId":1961,"exception":"[object] (ErrorException(code: 0): Undefined index: first_air_date (View: /var/www/html/resources/views/torrent/torrent.blade.php) at /var/www/html/storage/framework/views/107310da04da0a1f889ab5a0ac12013ae1fbeae0.php:671, ErrorException(code: 0): Undefined index: first_air_date at /var/www/html/storage/framework/views/107310da04da0a1f889ab5a0ac12013ae1fbeae0.php:671)

### Steps To Reproduce The Problem:
1. just added tmdb id from last update gives error.500
2.
3.

**Comment by HDVinnie** [comment]
Provide the TMDB ID so can debug.

**Comment by Nap4k** [comment]
https://www.themoviedb.org/movie/535144-sonchiriya?language=en-US
