### ISSUE TITLE
Login with username or email

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D#689]
### Issue Type
- [x] Enhancement

### End User Info
-- UNIT3D Version: 1.9.2

Hi, is possible to set the system to login with username OR email? 

I ask it because we have tremendous problems with the users who recover their password (in our case several thousand) and when filling out the recovery form with the email and save the data in the browser then on the login screen the email is saved in the field where the username should go, and they had to recover password EACH time visit our site. This is a user fault, but TOO common. Maybe is possible to login also with email doing some tweak.

Thanks

**Comment by HDVinnie** [comment]
Im somewhat against this. Offering to login with both username and email just adds one more opening for a account to be hacked. More so brute force attacks from botnets. If your members are that `dumb` just add a notice message to you login page.

**Comment by LayerCorp** [comment]
Notice message are already there... since day zero... even with this we have this massive problem.

**Comment by HDVinnie** [comment]
Ok then implement this yourself if its what you `want` for your site.
