### ISSUE TITLE
Download without speed when using ipv6 setting

### ISSUE THREAD

**Issue by buaapyj** [HDInnovations/UNIT3D#699]
Issue Type
- [X] Enhancement

End User Info
-- UNIT3D Version: Currently Running UNIT3D Nex-Gen Torrent Tracker v1.9.2

-- Laravel Version: Laravel Framework 5.8.7

-- PHP Version:

-- Database Driver & Version: mysql 5.7

-- Web Server Driver & Version: nginx，nginx version: nginx/1.15.8

-- OS Driver and Version: ubuntu 16.04

Expected Behavior:
First, I make a torret and issue the torrent from the UNIT3D website,  then I download a torrent from another pc.
If I use the ipv6 address as the tracker ip,download task without speed.
when I change the ip address as the v4. It works.
Ensure my pc is well, I added V6 address as a user manually in utorrent, then the task have speed.

Actual Behavior:
Trakcer seems to recognize the ipv6 address, but I don't know why it was not sent to the client.
![image](https://user-images.githubusercontent.com/25047090/56867954-ac12ff00-6a1e-11e9-85d1-7db81f51f710.png)

Steps To Reproduce The Problem:

First, I wonder to know if the tracker support IPV6?
If need some setting, plz teach me.

**Comment by HDVinnie** [comment]
@buaapyj thanks for the report. I am going to do some testing and will get back to you.

**Comment by buaapyj** [comment]
> @buaapyj thanks for the report. I am going to do some testing and will get back to you.
If you have anything that I need to do, you can let me do it.

**Comment by HDVinnie** [comment]
No nothing your end. Our announce needs to be adjusted to IPV6 support.

**Comment by buaapyj** [comment]
> No nothing your end. Our announce needs to be adjusted to IPV6 support.

I mean if you have any v6 test need to do

**Comment by masterfo78** [comment]
unfortunately has to turn on again. We have users who have ipv6 and the credited no upload.

I have also fixed with me no ipv6 address in the peers displayed

**Comment by buaapyj** [comment]
> 不幸的是必须再次开启。我们的用户拥有ipv6并且没有上传。
> 
> 我也修复了我在同行显示的没有ipv6地址

can you provide the screenshot result by click "View Peers" in torrent detail page.

**Comment by masterfo78** [comment]
https://i.gyazo.com/bf5d4f354fc582e07579d4287a2eee06.png

**Comment by buaapyj** [comment]
> https://i.gyazo.com/bf5d4f354fc582e07579d4287a2eee06.png

It's not a bug, you should let your website(especially your announce url) support ipv6，that's means your website server must have v6 address and your nginx open the listen of v6.

**Comment by masterfo78** [comment]
Do you have an instruction how I get my system on v6. ubuntu 16.04

**Comment by masterfo78** [comment]
the instructions I have found are shit

**Comment by buaapyj** [comment]
> the instructions I have found are shit

ifconfig is useful to judge if you have v6 address. 
if you make sure have v6 adress then your domain must have AAAAA(v6) DNS records.
you can test your domain support by this website.
[(https://mxtoolbox.com/IPv6.aspx)]

**Comment by masterfo78** [comment]
I have a godaddy domain.
go there on dns and to the domain.

enter AAAA my domain name.
then ipv6 address. is that OK

**Comment by buaapyj** [comment]
> I have a godaddy domain.
> go there on dns and to the domain.
> 
> enter AAAA my domain name.
> then ipv6 address. is that OK

first you should make sure your v6 address is available（can you provide your ifconfig result in your server）

**Comment by masterfo78** [comment]
https://pastebin.com/raw/3X9v35JF

**Comment by buaapyj** [comment]
unfortunately，the result means you don't have a available v6 address. the `fe80::` is a local address.
you should connect with your isp if the server is a private server
or connect with the Service provider if the server is a cloud server.

**Comment by HDVinnie** [comment]
You also need to keep in mind peers is per session. Check there history for upload of all sessions totaled.

**Comment by masterfo78** [comment]
I have now tested over 1 week with the users with ipv6 who have no upload

**Comment by buaapyj** [comment]
> I have now tested over 1 week with the users with ipv6 who have no upload

I will test this situation immediately

**Comment by masterfo78** [comment]
I looked at my provider and have a ipv6 block.

2001: 0bc8 .....

**Comment by buaapyj** [comment]
can you provide your domain

**Comment by masterfo78** [comment]
the provider wants to look at it again.
but what would be good if you can turn off the profile for the user have the ipv6. code from another source where that works. https://pastebin.com/raw/hTuCuRmS

**Comment by buaapyj** [comment]
I have test the website and announce system in ipv4 situation, it works well.(my pc have v4 and v6 address), I resolve my website domain by v4 addres(A record).

**Comment by masterfo78** [comment]
which website did you test? yours
