### ISSUE TITLE
Invalid Request Type: Client Request Was Not A HTTP GET

### ISSUE THREAD

**Issue by fcofrank36** [HDInnovations/UNIT3D#710]
### Issue Type
- [X] Technical Discussion
- [X] Question

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: 5.8.7

-- PHP Version: 7.3

-- Database Driver & Version: 5.7.25-0ubuntu0.18.04.2

-- Web Server Driver & Version:  nginx/1.15.8

### Expected Behavior:
![1234](https://user-images.githubusercontent.com/43528045/57002294-58262880-6b8c-11e9-8b3c-b0b0e1656d38.png)

![12345](https://user-images.githubusercontent.com/43528045/57002397-07fb9600-6b8d-11e9-9174-2644b7a22611.png)
these clients are used and in both gives the same message

### Steps To Reproduce The Problem:
1.  With the last update released when uploading a new torrent or an existing torrent, this error occurs in the client.
Tracker: [Failure reason \ "Invalid Request Type: Client Request Was Not A HTTP GET. \"]

2.These two clients were used.
rtorrent/0.9.6/0.13.6
uTorrent/2040(21515)

**Comment by HDVinnie** [comment]
@fcofrank36 pull in the new update and see if that fixes it. Let me know.

**Comment by fcofrank36** [comment]
Solved with the last update, thank you very much.
