### ISSUE TITLE
Automated Installation Issue

### ISSUE THREAD

**Issue by owlg** [HDInnovations/UNIT3D#715]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [x] Technical Discussion
- [x] Question

### End User Info
-- UNIT3D Version: Latest 
-- Laravel Version: Latest
-- PHP Version: 7.2

-- Database Driver & Version:
MySQL, Latest
-- Web Server Driver & Version:
Latest
-- OS Driver and Version:
Ubuntu 19.04

### Actual Behavior:
Automated installer terminates with MySQL "data directory needs to be specified"

### Steps To Reproduce The Problem:
1. Doing sudo ./install.sh again
2. Running through unskippable questions
3.

### Possible Fix:
Resumes to install when installer terminates instead of running the whole process again.

**Comment by HDVinnie** [comment]
Installer related issues should be in the installer repo. Not here.
https://github.com/poppabear8883/UNIT3D-INSTALLER
