### ISSUE TITLE
Websites will lose css when using TLS1.3

### ISSUE THREAD

**Issue by haig233** [HDInnovations/UNIT3D#728]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

### Possible Fix:

Website CDN uses Cloudflare, CSS file loss occurs when TLS1.3 is turned on, hope to fix

**Comment by HDVinnie** [comment]
PLEASE use the template issue. End User Info is empty. There is a template for a reason. Your issues are always bland.

Where there any errors in your browser console? More info is needed.
