### ISSUE TITLE
Some minor issues with the swedish translation, (would be able to fix them)

### ISSUE THREAD

**Issue by pkmolle** [HDInnovations/UNIT3D#729]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [x] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

### Possible Fix:
Hit me up and ill see what i can do, the translation is very good overall but i saw some minor defects ;)

**Comment by HDVinnie** [comment]
feel free to submit a PR

**Comment by pkmolle** [comment]
https://i.ibb.co/RhxrCNp/pre.png

Some quick edits on the bar text :)

**Comment by HDVinnie** [comment]
Closed by @pkmolle PR's
