### ISSUE TITLE
How to set up the tacker communication cycle?

### ISSUE THREAD

**Issue by haig233** [HDInnovations/UNIT3D#733]
### Issue Type
- [x] Question

### End User Info
-- UNIT3D Version: #.#.#
1.9.2
-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

### Possible Fix:

How to set up the tacker communication cycle?

**Comment by HDVinnie** [comment]
> How to set up the tacker communication cycle?

Can you be a little more detailed on what you mean.

**Comment by haig233** [comment]
![-141583f7ebfbc286.png](https://i.loli.net/2019/05/13/5cd980974974f63996.png)
I think that communication with the server every 55 minutes is too long, I want to set up communication every 5 minutes.

**Comment by haig233** [comment]
The picture shows Simplified Chinese, which shows 53 minutes and 20 seconds from the next update.

**Comment by HDVinnie** [comment]
Every 5 minutes would be VERY unwise and quite dumb to be frank. The norm is 45min. UNIT3D generates a random interval each announce to help combat mass announces.
```
        $min = 2400; // 40 Minutes
        $max = 3600; // 60 Minutes
        $res['interval'] = rand($min, $max);
```

It can be found in the AnnounceController.php
