### ISSUE TITLE
Compatibility problems with MariaDB

### ISSUE THREAD

**Issue by TailsxKyuubi** [HDInnovations/UNIT3D#738]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: 5.8.x

-- PHP Version: 7.3

-- Database Driver & Version: MariaDB (mysql)

-- Web Server Driver & Version: nginx

-- OS Driver and Version: Ubuntu 18.04

In the migrations are coulumns with the type json. But the MariaDB Database Server has no native JSON support. The migration process is crashing as result. I have detected this bug on my test server.

### Possible Fix:
Changing all columns from the datatype json to text

**Comment by HDVinnie** [comment]
What version of MariaDB you using? Must be old.

**Comment by TailsxKyuubi** [comment]
10.1.38

**Comment by HDVinnie** [comment]
And the README says?
https://github.com/HDInnovations/UNIT3D#-white_check_mark-requirements

MariaDB 10.2.7 (July 12, 2017) added "JSON" as a datatype alias to facilitate replication from MySQL to MariaDB.
