### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D#753]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ X] Question

### End User Info
-- UNIT3D Version: 1.9.2

-- Laravel Version: 5.8.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version: nginx version: nginx/1.15.8

-- OS Driver and Version: ubuntu 16.04

### Steps To Reproduce The Problem:
1. can one delete these user ranks if one does not need them
2. Guest Validating Disabled Pruned
3.

**Comment by HDVinnie** [comment]
No there system required.
