### ISSUE TITLE
Donation System

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D#80]
- Donation System with Stripe, Paypal and Bitcoin support. 
- Supporter Group
- Supporter Badge
- Configurable Package Plans

**Comment by Darkspac3** [comment]
ADD support for free donation like coinhive.com

**Comment by HDVinnie** [comment]
are you referring to the coinhive javascript based miners? Like mine for upload credit or bon? If so they will not be added at this time as there insecure and can be easily jacked.

**Comment by Darkspac3** [comment]
No upload credit or bon, mine for package plans.
I do not know if it's easily hackable but I saw it on 2 trackers uses coinhive.com but we can create it or use another website

**Comment by HDVinnie** [comment]
Im sorry but at this time I will not be adding any coin miners into this codebase. If that changes down the road I will make it known.
