### ISSUE TITLE
laravel errors

### ISSUE THREAD

**Issue by Sahoo2019** [HDInnovations/UNIT3D#805]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [* ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: v1.9.3

-- Laravel Version: Ver. 5.8.21

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Actual Behavior:
include(/var/www/html/vendor/composer/../symfony/contracts/Translation/LocaleAwareInterface.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/var/www/html/vendor/composer/../symfony/contracts/Translation/LocaleAwareInterface.php): failed to open stream: No such file or directory at /var/www/html/vendor/composer/ClassLoader.php:444)

******************************

Object of class Carbon\Carbon could not be converted to int (View: /var/www/html/resources/views/blocks/online.blade.php) (View: /var/www/html/resources/views/blocks/online.blade.php) {"userId":51,"exception":"[object] (ErrorException(code: 0): Object of class Carbon\\Carbon could not be converted to int (View: /var/www/html/resources/views/blocks/online.blade.php) (View: /var/www/html/resources/views/blocks/online.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1682, ErrorException(code: 0): Object of class Carbon\\Carbon could not be converted to int (View: /var/www/html/resources/views/blocks/online.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1682, ErrorException(code: 0): Object of class Carbon\\Carbon could not be converted to int at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1682)
--

************************************************

### Steps To Reproduce The Problem:
1.errors coming in logs
2.
3.

**Comment by HDVinnie** [comment]
resolved in latest updates
