### ISSUE TITLE
It is recommended to add a seed secondary title

### ISSUE THREAD

**Issue by haig233** [HDInnovations/UNIT3D#816]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [x] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#
v1.9.3
-- Laravel Version: #.#.#

-- PHP Version:
7.2
-- Database Driver & Version:
MySQL5.7
-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

### It is recommended to add a seed secondary title

**Comment by skank** [comment]
Wow. Such information. 
Much Suggestion.

**Comment by HDVinnie** [comment]
Yet another bland issue by @haig233
