### ISSUE TITLE
Captcha at login and registration

### ISSUE THREAD

**Issue by drt420** [HDInnovations/UNIT3D#82]
Hello
I think you should add captcha (maybe google) at login and registration so that bot doesn't make auto accounts

**Comment by HDVinnie** [comment]
I agree with this.....although it needs to be deeply looked into. As most captcha systems are already cracked from botnets and whatnot. I mean theres one out there that can crack over 8 million different captcha systems including the famous Google ReCaptcha v.1 and v.2, Solve Media and Facebook-captcha. IMO its not as "beneficial" as some think.

**Comment by HDVinnie** [comment]
Has been added to register page only.
Get your account setup here: https://www.google.com/recaptcha/intro/android.html

Add your site key and secret key to captcha config and set enabled to true.

**Comment by Alastor-NBL** [comment]
Would you advise using or not using this HDVinne? I myself often find it infuriating and prefer something like 2FA which you are implementing.

**Comment by HDVinnie** [comment]
Seeing it would be impossible to use 2FA on the registration process I would advise using the ReCaptcha. ReCaptcha for registration process. 2FA would make sense for login only.

**Comment by Alastor-NBL** [comment]
Guys sorry for asking but is pxgamer a site that is live and could I possibly join it, please?

**Comment by Alastor-NBL** [comment]
https://www.google.com/recaptcha/admin#list
There are 3 options and which one would you suggest to use?
Thank you
