### ISSUE TITLE
Click user in chat

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D#823]
### Issue Type
- [ ] Bug Report
- [ X] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [X ] Question

### End User Info
-- UNIT3D Version: 1.9.3

-- Laravel Version: 5.8.23

-- PHP Version: php7.3.6-1+ubuntu16.04.1+deb.sury.org+1

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.Is that possible that you can install something.
one must always enter the name in the chat. It would be better if you can click on it and in the input window then so.

#username
2.
3.

**Comment by HDVinnie** [comment]
Not sure what your asking.....can you please be more clear.

**Comment by masterfo78** [comment]
ok again. make username in the chat clickable that you do not need to write the name anymore. just click on the name and he comes in the input bar

**Comment by masterfo78** [comment]
Can you do that now? that is always misty to write the username
