### ISSUE TITLE
"The slug field is required." Error prompt

### ISSUE THREAD

**Issue by EPSUSKY** [HDInnovations/UNIT3D#848]
When saving the title of the Chinese Name Forum, prompt "The slug field is required."

**Comment by HDVinnie** [comment]
sorry not much I can do there. php's `str_slug` can't handle non ascii characters.

**Comment by EPSUSKY** [comment]
May I ask if that's OK?

function make_slug($string) { 
    return preg_replace('/\s+/u', '-', trim($string)); 
} 

$slug = make_slug(" 这是一段测试文字 "); 
echo $slug;

**Comment by EPSUSKY** [comment]
Thank you very much.
