### ISSUE TITLE
Trying to get property 'releaseYear' of non-object

### ISSUE THREAD

**Issue by JP9k** [HDInnovations/UNIT3D#857]
### Issue Type
- [X] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#
1.9.4
-- Laravel Version: #.#.#
5.8.32
-- PHP Version:
7.3.8
-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:
Ubuntu 16.04

### Expected Behavior:
To show the Cards mode i Torrents

### Actual Behavior:
Giving a fault 500:

Trying to get property 'releaseYear' of non-object (View: /var/www/html/resources/views/torrent/cards.blade.php) {"userId":9,"exception":"[object] (ErrorException(code: 0): Trying to get property 'releaseYear' of non-object (View: /var/www/html/resources/views/torrent/cards.blade.php) at /var/www/html/storage/framework/views/a817b77f08207ab9f0cf0688758385f5f77da587.php:272, ErrorException(code: 0): Trying to get property 'releaseYear' of non-object at /var/www/html/storage/framework/views/a817b77f08207ab9f0cf0688758385f5f77da587.php:272)

### Steps To Reproduce The Problem:
1.Using IMDB/TMDB without release year
2.
3.

**Comment by HDVinnie** [comment]
Can you please provide a IMDB and TMDB ID for a single torrent doing this? For testing purposes.

**Comment by HDVinnie** [comment]
@JP9k Please provide the information requested above otherwise this issue will be closed.

**Comment by HDVinnie** [comment]
@JP9k 10 days have passed with no further info provided. Issue is now being closed. Feel free to re-open if have requested info.

**Comment by JP9k** [comment]
https://www.imdb.com/title/tt9749144/
