### ISSUE TITLE
Cannot Delete Torrents

### ISSUE THREAD

**Issue by TheHandman** [HDInnovations/UNIT3D#98]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I tried reuploading a torrent due to what I thought was my own incompetence, but to my surprise the initial upload was just fine. I had deleted that upload, but was surprised to find it wasn't deleted at all, and about 10 others were seeding it.

### Steps To Reproduce:
Press the "Delete Torrrent" button in uploads.
Receive a message from the system stating the torrent has been deleted.
Find that the torrent wasn't deleted.

**Comment by HDVinnie** [comment]
So I have done some debugging and it seems there is a issue deleting torrents that have been "REJECTED" by moderation. However "PENDING" and "APPROVED" torrents delete fine. @MrG01 said he will look into this a few days back so Im going to assign him.

**Comment by TheHandman** [comment]
Thanks!
